/**
 * Ap dung script SQL len GARAGE.FDB
 * Chay tung cau CREATE TABLE / CREATE INDEX / COMMIT rieng biet
 * de tranh loi parser SET TERM cua Firebird.
 */
const firebird = require('node-firebird');

const config = {
  host: '127.0.0.1',
  port: 3050,
  database: 'D:/Garage/GARAGE.FDB',
  user: 'SYSDBA',
  password: 'masterkey',
  page_size: 65536,
};

/* Danh sach cac cau lenh de chay. Moi phan tu la mot chuoi SQL hoan chinh.
   Procedure (CREATE OR ALTER PROCEDURE) phai chay rieng vi co SET TERM dac biet. */

const STATEMENTS = [

  // ===== 1. Tao bang TTRANGTHAIXE =====
  `CREATE TABLE TTRANGTHAIXE (
    ID                 VARCHAR(36) NOT NULL,
    NAME               VARCHAR(255) NOT NULL,
    NOTE               VARCHAR(500),
    STATUS             INTEGER DEFAULT 1 NOT NULL,
    USERMODIFIEDID     VARCHAR(36),
    TIMEMODIFIED       TIMESTAMP,
    TIMECREATED        TIMESTAMP,
    USERCREATEDID      VARCHAR(36) NOT NULL,
    DXEID              VARCHAR(36) NOT NULL,
    DKHACHHANGID       VARCHAR(36) NOT NULL,
    TTIEPNHANXEID      VARCHAR(36),
    TLENHSUACHUAID     VARCHAR(36),
    TBAOGIAID          VARCHAR(36),
    TRANGTHAI          INTEGER DEFAULT 0 NOT NULL,
    NGAY_VAO           TIMESTAMP,
    NGAY_TRANGTHAI     TIMESTAMP,
    NGAY_DUKIEN        TIMESTAMP,
    DNHANVIENKTVID     VARCHAR(36),
    DNHANVIENCOOVANID  VARCHAR(36),
    LYDO               VARCHAR(1000),
    GHICHU             VARCHAR(1000),
    MUCUU_TIEN         INTEGER DEFAULT 1,
    DCUAHANGID         VARCHAR(36),
    CONSTRAINT PK_TTRANGTHAIXE PRIMARY KEY (ID)
  )`,

  `CREATE INDEX IDX_TTRANGTHAIXE_DXE ON TTRANGTHAIXE (DXEID, STATUS)`,
  `CREATE INDEX IDX_TTRANGTHAIXE_TRANGTHAI ON TTRANGTHAIXE (TRANGTHAI)`,
  `CREATE INDEX IDX_TTRANGTHAIXE_KH ON TTRANGTHAIXE (DKHACHHANGID)`,
  `CREATE INDEX IDX_TTRANGTHAIXE_NGAY ON TTRANGTHAIXE (NGAY_VAO)`,

  // ===== 2. Tao bang TLICHSUTRANGTHAI =====
  `CREATE TABLE TLICHSUTRANGTHAI (
    ID                 VARCHAR(36) NOT NULL,
    NOTE               VARCHAR(500),
    STATUS             INTEGER DEFAULT 1 NOT NULL,
    USERMODIFIEDID     VARCHAR(36),
    TIMEMODIFIED       TIMESTAMP,
    TIMECREATED        TIMESTAMP,
    USERCREATEDID      VARCHAR(36) NOT NULL,
    TTRANGTHAIXEID     VARCHAR(36) NOT NULL,
    DXEID              VARCHAR(36) NOT NULL,
    TRANGTHAI_CU       INTEGER,
    TRANGTHAI_MOI      INTEGER NOT NULL,
    NGAY               TIMESTAMP,
    DNHANVIENID        VARCHAR(36),
    LYDO               VARCHAR(1000),
    GHICHU             VARCHAR(1000),
    STT                INTEGER DEFAULT 0,
    CONSTRAINT PK_TLICHSUTRANGTHAI PRIMARY KEY (ID)
  )`,

  `CREATE INDEX IDX_LSTRANGTHAI_XE ON TLICHSUTRANGTHAI (DXEID, NGAY)`,
  `CREATE INDEX IDX_LSTRANGTHAI_TTX ON TLICHSUTRANGTHAI (TTRANGTHAIXEID)`,

  // ===== 3. TWORKFLOWMAP =====
  `CREATE TABLE TWORKFLOWMAP (
    ID                 VARCHAR(36) NOT NULL,
    STATUS             INTEGER DEFAULT 1 NOT NULL,
    USERCREATEDID      VARCHAR(36) NOT NULL,
    TIMECREATED        TIMESTAMP,
    STT_WORKFLOW       INTEGER NOT NULL,
    TEN                VARCHAR(100) NOT NULL,
    MAU                VARCHAR(10),
    ICON               VARCHAR(20),
    TRANGTHAI_TN       INTEGER,
    TRANGTHAI_CD       INTEGER,
    TRANGTHAI_LSC      INTEGER,
    IS_TERMINAL        INTEGER DEFAULT 0,
    NEXT_STT           INTEGER,
    CONSTRAINT PK_TWORKFLOWMAP PRIMARY KEY (ID)
  )`,

  `CREATE UNIQUE INDEX IDX_WORKFLOWMAP_STT ON TWORKFLOWMAP (STT_WORKFLOW)`,

  // ===== 4. Seed workflow map (5 trang thai) =====
  `INSERT INTO TWORKFLOWMAP (ID, USERCREATEDID, TIMECREATED, STT_WORKFLOW, TEN, MAU, ICON, TRANGTHAI_TN, TRANGTHAI_CD, TRANGTHAI_LSC, IS_TERMINAL, NEXT_STT) VALUES (GEN_UUID(), 'SYSTEM', CURRENT_TIMESTAMP, 0, 'Tiep nhan & Bao gia', 'blue', 'inbox', 1, 2, 0, 0, 1)`,
  `INSERT INTO TWORKFLOWMAP (ID, USERCREATEDID, TIMECREATED, STT_WORKFLOW, TEN, MAU, ICON, TRANGTHAI_TN, TRANGTHAI_CD, TRANGTHAI_LSC, IS_TERMINAL, NEXT_STT) VALUES (GEN_UUID(), 'SYSTEM', CURRENT_TIMESTAMP, 1, 'Xac nhan sua chua', 'yellow', 'thumbs-up', 1, 3, 1, 0, 2)`,
  `INSERT INTO TWORKFLOWMAP (ID, USERCREATEDID, TIMECREATED, STT_WORKFLOW, TEN, MAU, ICON, TRANGTHAI_TN, TRANGTHAI_CD, TRANGTHAI_LSC, IS_TERMINAL, NEXT_STT) VALUES (GEN_UUID(), 'SYSTEM', CURRENT_TIMESTAMP, 2, 'Dang sua', 'red', 'wrench', 1, 3, 1, 0, 3)`,
  `INSERT INTO TWORKFLOWMAP (ID, USERCREATEDID, TIMECREATED, STT_WORKFLOW, TEN, MAU, ICON, TRANGTHAI_TN, TRANGTHAI_CD, TRANGTHAI_LSC, IS_TERMINAL, NEXT_STT) VALUES (GEN_UUID(), 'SYSTEM', CURRENT_TIMESTAMP, 3, 'Giao xe', 'purple', 'check-double', 3, 4, 5, 0, 4)`,
  `INSERT INTO TWORKFLOWMAP (ID, USERCREATEDID, TIMECREATED, STT_WORKFLOW, TEN, MAU, ICON, TRANGTHAI_TN, TRANGTHAI_CD, TRANGTHAI_LSC, IS_TERMINAL, NEXT_STT) VALUES (GEN_UUID(), 'SYSTEM', CURRENT_TIMESTAMP, 4, 'Hoan thanh', 'green', 'check-circle', 2, 4, 3, 1, NULL)`,
];

const PROC_SQL = `
CREATE OR ALTER PROCEDURE SP_CHUYEN_TRANGTHAI (
    P_DXEID VARCHAR(36),
    P_TRANGTHAI_MOI INTEGER,
    P_DNHANVIENID VARCHAR(36),
    P_LYDO VARCHAR(1000),
    P_GHICHU VARCHAR(1000)
)
RETURNS (
    R_TTRANGTHAIXEID VARCHAR(36),
    R_SUCCESS INTEGER
)
AS
DECLARE VARIABLE V_TTRANGTHAIXEID VARCHAR(36);
DECLARE VARIABLE V_TRANGTHAI_CU INTEGER;
DECLARE VARIABLE V_LICHSU_ID VARCHAR(36);
DECLARE VARIABLE V_TTIEPNHANXEID VARCHAR(36);
DECLARE VARIABLE V_TLENHSUACHUAID VARCHAR(36);
DECLARE VARIABLE V_TCHANDOANID VARCHAR(36);
DECLARE VARIABLE V_STT INTEGER;
DECLARE VARIABLE V_DKHACHHANGID VARCHAR(36);
DECLARE VARIABLE V_TN INTEGER;
DECLARE VARIABLE V_CD INTEGER;
DECLARE VARIABLE V_LSC INTEGER;
BEGIN
  SELECT FIRST 1 ID, TRANGTHAI, TTIEPNHANXEID, TLENHSUACHUAID
    FROM TTRANGTHAIXE
   WHERE DXEID = :P_DXEID AND STATUS = 1
    INTO :V_TTRANGTHAIXEID, :V_TRANGTHAI_CU, :V_TTIEPNHANXEID, :V_TLENHSUACHUAID;

  IF (V_TTRANGTHAIXEID IS NULL) THEN
  BEGIN
    SELECT DKHACHHANGID FROM DXE WHERE ID = :P_DXEID INTO :V_DKHACHHANGID;

    V_TTRANGTHAIXEID = GEN_UUID();
    INSERT INTO TTRANGTHAIXE
      (ID, NAME, STATUS, USERCREATEDID, TIMECREATED,
       DXEID, DKHACHHANGID, TRANGTHAI, NGAY_VAO, NGAY_TRANGTHAI,
       DNHANVIENKTVID, LYDO, GHICHU)
    VALUES
      (:V_TTRANGTHAIXEID, 'Workflow xe', 1, :P_DNHANVIENID, CURRENT_TIMESTAMP,
       :P_DXEID, :V_DKHACHHANGID, :P_TRANGTHAI_MOI, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
       :P_DNHANVIENID, :P_LYDO, :P_GHICHU);

    V_TRANGTHAI_CU = NULL;
    V_STT = 0;
  END
  ELSE
  BEGIN
    UPDATE TTRANGTHAIXE
       SET TRANGTHAI = :P_TRANGTHAI_MOI,
           NGAY_TRANGTHAI = CURRENT_TIMESTAMP,
           USERMODIFIEDID = :P_DNHANVIENID,
           TIMEMODIFIED = CURRENT_TIMESTAMP,
           LYDO = :P_LYDO,
           GHICHU = :P_GHICHU
     WHERE ID = :V_TTRANGTHAIXEID;

    SELECT COUNT(*) FROM TLICHSUTRANGTHAI WHERE TTRANGTHAIXEID = :V_TTRANGTHAIXEID INTO :V_STT;
    V_STT = COALESCE(V_STT, 0);
  END

  SELECT TRANGTHAI_TN, TRANGTHAI_CD, TRANGTHAI_LSC
    FROM TWORKFLOWMAP
   WHERE STT_WORKFLOW = :P_TRANGTHAI_MOI
    INTO :V_TN, :V_CD, :V_LSC;

  IF (V_TTIEPNHANXEID IS NOT NULL AND V_TN IS NOT NULL) THEN
    UPDATE TTIEPNHANXE
       SET TRANGTHAI = :V_TN,
           USERMODIFIEDID = :P_DNHANVIENID,
           TIMEMODIFIED = CURRENT_TIMESTAMP
     WHERE ID = :V_TTIEPNHANXEID;

  IF (V_TLENHSUACHUAID IS NOT NULL AND V_LSC IS NOT NULL) THEN
    UPDATE TLENHSUACHUA
       SET TRANGTHAI = :V_LSC,
           USERMODIFIEDID = :P_DNHANVIENID,
           TIMEMODIFIED = CURRENT_TIMESTAMP
     WHERE ID = :V_TLENHSUACHUAID;

  IF (V_CD IS NOT NULL) THEN
  BEGIN
    SELECT FIRST 1 ID FROM TCHANDOAN
     WHERE DXEID = :P_DXEID AND STATUS = 1
     ORDER BY TIMECREATED DESC
      INTO :V_TCHANDOANID;
    IF (V_TCHANDOANID IS NOT NULL) THEN
      UPDATE TCHANDOAN
         SET TRANGTHAI = :V_CD,
             USERMODIFIEDID = :P_DNHANVIENID,
             TIMEMODIFIED = CURRENT_TIMESTAMP
       WHERE ID = :V_TCHANDOANID;
  END

  V_LICHSU_ID = GEN_UUID();
  INSERT INTO TLICHSUTRANGTHAI
    (ID, STATUS, USERCREATEDID, TIMECREATED,
     TTRANGTHAIXEID, DXEID, TRANGTHAI_CU, TRANGTHAI_MOI, NGAY,
     DNHANVIENID, LYDO, GHICHU, STT)
  VALUES
    (:V_LICHSU_ID, 1, :P_DNHANVIENID, CURRENT_TIMESTAMP,
     :V_TTRANGTHAIXEID, :P_DXEID, :V_TRANGTHAI_CU, :P_TRANGTHAI_MOI, CURRENT_TIMESTAMP,
     :P_DNHANVIENID, :P_LYDO, :P_GHICHU, :V_STT);

  R_TTRANGTHAIXEID = :V_TTRANGTHAIXEID;
  R_SUCCESS = 1;

  SUSPEND;
END
`;

async function exec(db, sql) {
  return new Promise((resolve, reject) => {
    db.query(sql, [], (err, result) => err ? reject(err) : resolve(result));
  });
}

async function main() {
  console.log('>>> Connecting to GARAGE.FDB...');
  const db = await new Promise((res, rej) =>
    firebird.attach(config, (err, d) => err ? rej(err) : res(d))
  );

  let ok = 0, fail = 0;

  console.log(`>>> Running ${STATEMENTS.length} statements...`);
  for (let i = 0; i < STATEMENTS.length; i++) {
    const stmt = STATEMENTS[i];
    try {
      await exec(db, stmt);
      ok++;
      const preview = stmt.replace(/\s+/g, ' ').slice(0, 70);
      console.log(`  OK [${i + 1}/${STATEMENTS.length}] ${preview}...`);
    } catch (e) {
      fail++;
      console.error(`  FAIL [${i + 1}/${STATEMENTS.length}]: ${e.message}`);
      console.error(`    ${stmt.replace(/\s+/g, ' ').slice(0, 200)}`);
    }
  }

  console.log(`\n>>> Creating stored procedure SP_CHUYEN_TRANGTHAI...`);
  try {
    await exec(db, PROC_SQL);
    console.log('  OK PROC');
    ok++;
  } catch (e) {
    fail++;
    console.error('  FAIL PROC:', e.message);
  }

  await exec(db, 'SELECT 1 FROM RDB$DATABASE');

  db.detach();
  console.log(`\n>>> DONE: ${ok} ok, ${fail} fail`);
  process.exit(fail > 0 ? 1 : 0);
}

main().catch(e => {
  console.error('FATAL:', e);
  process.exit(1);
});
