const fs=require('fs');const path=require('path');const crypto=require('crypto');const db=require('./src/db');const {types}=require('./src/services/documentPrint');const migrateConfig=require('./migrate_system_config_templates');
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');
function template(type){let n=0;const text=(value,x,y,w,h,extra='')=>`<TextObject Name="T${++n}" Left="${x}" Top="${y}" Width="${w}" Height="${h}" Text="${esc(value)}" Font="Arial, 10pt" CanGrow="true" ${extra}/>`;
const descriptive=type.layout==='text';const cols=type.layout==='barcode'?[['Mã phụ tùng','ItemCode',0,170],['Tên phụ tùng','ItemName',170,355],['Giá bán','AmountText',525,193]]:descriptive?[['Nội dung','ItemName',0,240],['Thông tin','ValueText',240,478]]:[['STT','Index',0,35],['Hạng mục / phụ tùng','ItemName',35,255],['ĐVT','Unit',290,45],['SL','QuantityText',335,45],['Đơn giá','UnitPriceText',380,145],['Thành tiền','AmountText',525,193]];
const parameters=['CompanyName','CompanyAddress','CompanyPhone','DocTitle','DocNumber','DocDate','CustomerName','Contact','VehiclePlate','Description','Extra','SummaryText','FooterNote'];
const rowCols=['Index','ItemName','ItemCode','Unit','QuantityText','UnitPriceText','AmountText','ValueText','Note','BARCODE'];
return `<?xml version="1.0" encoding="utf-8"?><Report DoublePass="true" ScriptLanguage="CSharp" ReportInfo.Description="Biểu mẫu GARA; dữ liệu chứng từ đã lưu"><Dictionary><TableDataSource Name="Table0" ReferenceName="Data.Table0" DataType="System.Int32" Enabled="true">${rowCols.map(k=>`<Column Name="${k}" DataType="System.String"/>`).join('')}</TableDataSource>${parameters.map(k=>`<Parameter Name="${k}" DataType="System.String"/>`).join('')}</Dictionary><ReportPage Name="Page1" PaperWidth="210" PaperHeight="297" LeftMargin="10" RightMargin="10" TopMargin="10" BottomMargin="10"><ReportTitleBand Name="Title" Width="718.2" Height="225" CanGrow="true">${text('[CompanyName]',0,0,718,24,'HorzAlign="Center"')}${text('[CompanyAddress] | [CompanyPhone]',0,28,718,24,'HorzAlign="Center"')}${text('[DocTitle]',0,60,718,30,'HorzAlign="Center"')}${text('Số: [DocNumber]     Ngày: [DocDate]',0,100,718,24)}${text('Khách hàng / đối tác: [CustomerName]     ĐT: [Contact]',0,130,718,24)}${text('Biển số xe: [VehiclePlate]',0,160,718,24)}${text('[Description]',0,190,718,30)}</ReportTitleBand><DataBand Name="Rows" Width="718.2" Height="${type.layout==='barcode'?135:52}" DataSource="Table0" CanGrow="true">${cols.map(([label,key,x,w])=>text(`[Table0.${key}]`,x,0,w,27,'Border.Lines="All"')).join('')}${text('[Table0.Note]',35,29,683,21)}${type.layout==='barcode'?'<BarcodeObject Name="Code" Top="55" Width="260" Height="70" DataColumn="Table0.BARCODE" Barcode="Code128"/>':''}<DataHeaderBand Name="Columns" Width="718.2" Height="28" RepeatOnEveryPage="true">${cols.map(([label,key,x,w])=>text(label,x,0,w,28,'Border.Lines="All" Fill.Color="Gainsboro"')).join('')}</DataHeaderBand></DataBand><ReportSummaryBand Name="Summary" Width="718.2" Height="160" CanGrow="true">${text('[SummaryText]',0,10,718,30,'HorzAlign="Right"')}${text('[Extra]',0,50,718,30)}${text('[FooterNote]',0,100,718,35,'HorzAlign="Center"')}</ReportSummaryBand><PageFooterBand Name="Footer" Width="718.2" Height="24">${text('Trang [Page]',0,0,718,24,'HorzAlign="Right"')}</PageFooterBand></ReportPage></Report>`;}
async function migrate(){await migrateConfig();const before=await db.query('SELECT ID,NAME,TEXTVALUE,OTHERCONFIG FROM SCONFIG WHERE STATUS=30');const backup=path.join(__dirname,`system-config-templates-backup-${Date.now()}.json`);fs.writeFileSync(backup,JSON.stringify(before,null,2));const root=path.join(__dirname,'templates','gara');fs.mkdirSync(root,{recursive:true});await db.transaction(async(q,execute)=>{for(const type of types){const hex=crypto.createHash('sha256').update('GARA-NATIVE-PRINT-v1:'+type.key).digest('hex');const id=`${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20,32)}`;const xml=template(type);fs.writeFileSync(path.join(root,`${type.key}.frx`),xml);const existing=await q('SELECT ID FROM STEMPLATE WHERE ID=?',[id]);if(!existing.length)await execute('INSERT INTO STEMPLATE (ID,NAME,STATUS,USERCREATEDID,TIMECREATED,TEMPLATE,REPORTBASE) VALUES (?,?,30,\'SYSTEM\',CURRENT_TIMESTAMP,?,0)',[id,`GARA - ${type.label} A4`,Buffer.from(xml)]);if(existing.length && process.argv.includes('--refresh-generated'))await execute('UPDATE STEMPLATE SET TEMPLATE=?,TIMEMODIFIED=CURRENT_TIMESTAMP WHERE ID=?',[Buffer.from(xml),id]);const row=before.find(r=>r.NAME===type.key);const ids=JSON.parse(row.OTHERCONFIG||'[]');if(!ids.includes(id)){ids.push(id);await execute('UPDATE SCONFIG SET OTHERCONFIG=?,TEXTVALUE=?,TIMEMODIFIED=CURRENT_TIMESTAMP WHERE ID=?',[JSON.stringify(ids),id,row.ID]);}console.log(type.key,id);}});console.log('Backup:',backup);}
if(require.main===module)migrate().catch(e=>{console.error(e);process.exitCode=1;});module.exports={migrate,template};
