const db = require('./src/db');
const definitions = {
 PRINT_STATIONS: `ID VARCHAR(36) NOT NULL PRIMARY KEY, NAME VARCHAR(120), TOKENHASH VARCHAR(64), LASTSEEN TIMESTAMP, REVOKED SMALLINT DEFAULT 0, VERSION VARCHAR(40)`,
 PRINT_PAIRINGS: `ID VARCHAR(36) NOT NULL PRIMARY KEY, TICKETHASH VARCHAR(64) NOT NULL, EXPIRES TIMESTAMP NOT NULL, USED SMALLINT DEFAULT 0`,
 PRINT_PRINTERS: `ID VARCHAR(36) NOT NULL PRIMARY KEY, STATIONID VARCHAR(36) NOT NULL, NAME VARCHAR(200) NOT NULL, ENABLED SMALLINT DEFAULT 0, WIDTHMM INTEGER DEFAULT 80`,
 PRINT_ROUTES: `TYPEKEY VARCHAR(80) NOT NULL PRIMARY KEY, PRINTERID VARCHAR(36) NOT NULL`,
 PRINT_JOBS: `ID VARCHAR(36) NOT NULL PRIMARY KEY, USERID VARCHAR(36) NOT NULL, TYPEKEY VARCHAR(80) NOT NULL, RECORDID VARCHAR(80) NOT NULL, TEMPLATEID VARCHAR(36), PRINTERID VARCHAR(36) NOT NULL, STATIONID VARCHAR(36) NOT NULL, PRINTERNAME VARCHAR(200), WIDTHMM INTEGER, COPIES INTEGER, STATE VARCHAR(30), IDEMKEY VARCHAR(80) NOT NULL, PDFHASH VARCHAR(64), CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP, EXPIRES TIMESTAMP, LEASEUNTIL TIMESTAMP, DETAIL VARCHAR(500), PDFDATA BLOB SUB_TYPE 0`,
 PRINT_JOB_EVENTS: `ID VARCHAR(36) NOT NULL PRIMARY KEY, JOBID VARCHAR(36) NOT NULL, STATE VARCHAR(30), DETAIL VARCHAR(500), CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP`,
};
async function migrate() {
 for (const [name, fields] of Object.entries(definitions)) {
  const exists = await db.query('SELECT RDB$RELATION_NAME FROM RDB$RELATIONS WHERE RDB$RELATION_NAME=?', [name]);
  if (!exists.length) { await db.execute(`CREATE TABLE ${name} (${fields})`); console.log('Created', name); }
 }
 for (const [name, sql] of Object.entries({ PRINT_JOBS_IDEM: 'CREATE UNIQUE INDEX PRINT_JOBS_IDEM ON PRINT_JOBS (USERID, IDEMKEY)', PRINT_JOBS_QUEUE: 'CREATE INDEX PRINT_JOBS_QUEUE ON PRINT_JOBS (STATIONID, STATE)', PRINT_PRINTER_STATION: 'CREATE UNIQUE INDEX PRINT_PRINTER_STATION ON PRINT_PRINTERS (STATIONID, NAME)' })) {
  if (!(await db.query('SELECT RDB$INDEX_NAME FROM RDB$INDICES WHERE RDB$INDEX_NAME=?', [name])).length) await db.execute(sql);
 }
}
if (require.main === module) migrate().catch(e => { console.error(e.message); process.exitCode=1; });
module.exports={migrate};
