const fs=require('fs');const path=require('path');const crypto=require('crypto');const db=require('./src/db');const {templateFilter}=require('./src/services/systemConfigOptions');
const files=['Mẫu A4 nằm ngang.frx','Mẫu A4 nằm đứng.frx','Mẫu 80.frx'];
function templateId(file){const hex=crypto.createHash('sha256').update('GARA-RECEPTION-USER-v1:'+file).digest('hex');return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20,32)}`;}
async function migrate(){const before=await db.query("SELECT ID,NAME,TEXTVALUE,OTHERCONFIG,SCONFIGGROUPID FROM SCONFIG WHERE NAME IN ('MauPhieuTiepNhan','CompanyName','CompanyLogo')");fs.writeFileSync(path.join(__dirname,`system-config-templates-backup-${Date.now()}.json`),JSON.stringify(before,null,2));
await db.transaction(async(q,execute,uuid)=>{const company=before.find(row=>row.NAME==='CompanyName');if(!company)throw new Error('Thiếu nhóm thông tin công ty.');if(!before.some(row=>row.NAME==='CompanyLogo'))await execute("INSERT INTO SCONFIG (ID,NAME,CAPTION,STATUS,CONTROLTYPE,DATATYPE,SCONFIGGROUPID,SORTORDER,MOREDETAIL,USERCREATEDID,TIMECREATED) VALUES (?,'CompanyLogo','Logo công ty',30,'4',5,?,0,'Chọn PNG/JPG tối đa 20 MB; tự nén trước khi lưu. Logo được dùng trên các mẫu in GARA.','SYSTEM',CURRENT_TIMESTAMP)",[uuid(),company.SCONFIGGROUPID]);
const config=before.find(row=>row.NAME==='MauPhieuTiepNhan');if(!config)throw new Error('Thiếu cấu hình Mẫu tiếp nhận xe.');const ids=templateFilter(config.OTHERCONFIG)?.ids||[];
for(const file of files){const id=templateId(file);const content=fs.readFileSync(path.join(__dirname,'templates','reception',file));const rows=await q('SELECT ID FROM STEMPLATE WHERE ID=?',[id]);if(!rows.length)await execute("INSERT INTO STEMPLATE (ID,NAME,STATUS,USERCREATEDID,TIMECREATED,TEMPLATE,REPORTBASE) VALUES (?,?,30,'SYSTEM',CURRENT_TIMESTAMP,?,0)",[id,file.replace('.frx','')+' - Tiếp nhận xe',content]);if(!ids.includes(id))ids.push(id);console.log(file,id);}
const current=config.TEXTVALUE;const defaultId=!current||current==='edccb743-cf5c-9fa3-e185-8052b586db92'?templateId(files[1]):current;
await execute('UPDATE SCONFIG SET OTHERCONFIG=?,TEXTVALUE=?,TIMEMODIFIED=CURRENT_TIMESTAMP WHERE ID=?',[JSON.stringify(ids),defaultId,config.ID]);});}
if(require.main===module)migrate().catch(e=>{console.error(e);process.exitCode=1;});module.exports={migrate,files,templateId};
