/**
 * Tao lai stored procedure SP_CHUYEN_TRANGTHAI, khong dung GEN_UUID
 * (vi trong Firebird 2.5 GEN_UUID tra ve 16 bytes binary)
 * UUID se duoc truyen tu JS qua tham so.
 */
const os = require('os');
try { os.userInfo(); } catch { os.userInfo = () => ({ username: process.env.USERNAME || 'SYSTEM' }); }
const firebird = require('node-firebird');

const config = {
  host: '127.0.0.1',
  port: 3050,
  database: 'D:/Garage/GARAGE.FDB',
  user: 'SYSDBA',
  password: 'masterkey',
  page_size: 65536,
};

const PROC_SQL = `
CREATE OR ALTER PROCEDURE SP_CHUYEN_TRANGTHAI (
    P_DXEID VARCHAR(36),
    P_TRANGTHAI_MOI INTEGER,
    P_DNHANVIENID VARCHAR(36),
    P_LYDO VARCHAR(1000),
    P_GHICHU VARCHAR(1000),
    P_NEW_TTRANGTHAIXEID VARCHAR(36),
    P_NEW_LICHSU_ID VARCHAR(36)
)
RETURNS (
    R_TTRANGTHAIXEID VARCHAR(36),
    R_SUCCESS INTEGER
)
AS
DECLARE VARIABLE V_TTRANGTHAIXEID VARCHAR(36);
DECLARE VARIABLE V_TRANGTHAI_CU INTEGER;
DECLARE VARIABLE V_TTIEPNHANXEID VARCHAR(36);
DECLARE VARIABLE V_TLENHSUACHUAID VARCHAR(36);
DECLARE VARIABLE V_TCHANDOANID VARCHAR(36);
DECLARE VARIABLE V_STT INTEGER;
DECLARE VARIABLE V_DKHACHHANGID VARCHAR(36);
DECLARE VARIABLE V_TN INTEGER;
DECLARE VARIABLE V_CD INTEGER;
DECLARE VARIABLE V_LSC INTEGER;
BEGIN
  SELECT FIRST 1 ID, TRANGTHAI, TTIEPNHANXEID, TLENHSUACHUAID
    FROM TTRANGTHAIXE
   WHERE DXEID = :P_DXEID AND STATUS = 1
   ORDER BY CASE WHEN TRANGTHAI < 4 THEN 0 ELSE 1 END,
            NGAY_TRANGTHAI DESC, TIMECREATED DESC
    INTO :V_TTRANGTHAIXEID, :V_TRANGTHAI_CU, :V_TTIEPNHANXEID, :V_TLENHSUACHUAID;

  IF (V_TTRANGTHAIXEID IS NULL) THEN
  BEGIN
    SELECT DKHACHHANGID FROM DXE WHERE ID = :P_DXEID INTO :V_DKHACHHANGID;

    V_TTRANGTHAIXEID = :P_NEW_TTRANGTHAIXEID;
    INSERT INTO TTRANGTHAIXE
      (ID, NAME, STATUS, USERCREATEDID, TIMECREATED,
       DXEID, DKHACHHANGID, TRANGTHAI, NGAY_VAO, NGAY_TRANGTHAI,
       DNHANVIENKTVID, LYDO, GHICHU)
    VALUES
      (:V_TTRANGTHAIXEID, 'Workflow xe', 1, :P_DNHANVIENID, CURRENT_TIMESTAMP,
       :P_DXEID, :V_DKHACHHANGID, :P_TRANGTHAI_MOI, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
       :P_DNHANVIENID, :P_LYDO, :P_GHICHU);

    V_TRANGTHAI_CU = NULL;
    V_STT = 0;
  END
  ELSE
  BEGIN
    UPDATE TTRANGTHAIXE
       SET TRANGTHAI = :P_TRANGTHAI_MOI,
           NGAY_TRANGTHAI = CURRENT_TIMESTAMP,
           USERMODIFIEDID = :P_DNHANVIENID,
           TIMEMODIFIED = CURRENT_TIMESTAMP,
           LYDO = :P_LYDO,
           GHICHU = :P_GHICHU
     WHERE ID = :V_TTRANGTHAIXEID;

    SELECT COUNT(*) FROM TLICHSUTRANGTHAI WHERE TTRANGTHAIXEID = :V_TTRANGTHAIXEID INTO :V_STT;
    V_STT = COALESCE(V_STT, 0);
  END

  SELECT TRANGTHAI_TN, TRANGTHAI_CD, TRANGTHAI_LSC
    FROM TWORKFLOWMAP
   WHERE STT_WORKFLOW = :P_TRANGTHAI_MOI
    INTO :V_TN, :V_CD, :V_LSC;

  IF (V_TTIEPNHANXEID IS NOT NULL AND V_TN IS NOT NULL) THEN
    UPDATE TTIEPNHANXE
       SET TRANGTHAI = :V_TN,
           USERMODIFIEDID = :P_DNHANVIENID,
           TIMEMODIFIED = CURRENT_TIMESTAMP
     WHERE ID = :V_TTIEPNHANXEID;

  IF (V_TLENHSUACHUAID IS NOT NULL AND V_LSC IS NOT NULL) THEN
    UPDATE TLENHSUACHUA
       SET TRANGTHAI = :V_LSC,
           USERMODIFIEDID = :P_DNHANVIENID,
           TIMEMODIFIED = CURRENT_TIMESTAMP
     WHERE ID = :V_TLENHSUACHUAID;

  IF (V_CD IS NOT NULL) THEN
  BEGIN
    SELECT FIRST 1 ID FROM TCHANDOAN
     WHERE DXEID = :P_DXEID AND STATUS = 1
     ORDER BY TIMECREATED DESC
      INTO :V_TCHANDOANID;
    IF (V_TCHANDOANID IS NOT NULL) THEN
      UPDATE TCHANDOAN
         SET TRANGTHAI = :V_CD,
             USERMODIFIEDID = :P_DNHANVIENID,
             TIMEMODIFIED = CURRENT_TIMESTAMP
       WHERE ID = :V_TCHANDOANID;
  END

  INSERT INTO TLICHSUTRANGTHAI
    (ID, STATUS, USERCREATEDID, TIMECREATED,
     TTRANGTHAIXEID, DXEID, TRANGTHAI_CU, TRANGTHAI_MOI, NGAY,
     DNHANVIENID, LYDO, GHICHU, STT)
  VALUES
    (:P_NEW_LICHSU_ID, 1, :P_DNHANVIENID, CURRENT_TIMESTAMP,
     :V_TTRANGTHAIXEID, :P_DXEID, :V_TRANGTHAI_CU, :P_TRANGTHAI_MOI, CURRENT_TIMESTAMP,
     :P_DNHANVIENID, :P_LYDO, :P_GHICHU, :V_STT);

  R_TTRANGTHAIXEID = :V_TTRANGTHAIXEID;
  R_SUCCESS = 1;

  SUSPEND;
END
`;

function exec(db, sql, params = []) {
  return new Promise((res, rej) => db.query(sql, params, (e, r) => e ? rej(e) : res(r)));
}

async function main() {
  const db = await new Promise((res, rej) =>
    firebird.attach(config, (err, d) => err ? rej(err) : res(d))
  );
  try {
    await exec(db, PROC_SQL);
    console.log('>>> SP_CHUYEN_TRANGTHAI recreated OK');
  } catch (e) {
    console.error('FAIL:', e.message);
  }
  db.detach();
}

main().catch(e => { console.error('FATAL:', e); process.exit(1); });
