const {test}=require('node:test');const assert=require('node:assert/strict');
const {reports,groups,permitted}=require('../src/services/reportCatalog');
const {calculate,validate,day}=require('../src/services/reportData');
const {xlsx,crc32}=require('../src/services/reportExport');
const report=id=>reports.find(r=>r.id===id);
test('11 groups, unique reports, unavailable reports have a specific reason',()=>{assert.equal(groups.length,11);assert.equal(new Set(reports.map(r=>r.id)).size,reports.length);assert.ok(reports.filter(r=>r.available===false).every(r=>r.reason&&r.source===null));});
test('dates reject invalid days and reversed ranges; Bangkok includes UTC day rollover',()=>{assert.throws(()=>validate({from:'2026-02-30'}));assert.throws(()=>validate({from:'2026-10-09',to:'2026-10-08'}));assert.throws(()=>validate({days:0.5}));assert.equal(day(new Date('2026-10-07T18:00:00Z')),'2026-10-08');});
test('money and salary reports require extra permissions for view and export',()=>{const user={permissions:{REPORTS:17}};assert.equal(permitted(user,report('receipts'),true),true);assert.equal(permitted(user,report('payroll')),false);assert.equal(permitted(user,report('stock-value')),false);assert.equal(permitted(user,report('staff-productivity')),false);user.permissions.EMPLOYEES=1;assert.equal(permitted(user,report('payroll'),true),true);user.permissions.REPORTS=1;assert.equal(permitted(user,report('payroll'),true),false);});
test('inventory opening includes pre-period movements; cancelled sources excluded by loader',()=>{const raw=[{id:'a',partId:'p',partCode:'P',name:'Part',warehouse:'A',date:'2026-09-01',received:10,issued:0},{id:'b',partId:'p',partCode:'P',name:'Part',warehouse:'A',date:'2026-10-01',received:0,issued:3},{id:'c',partId:'p',partCode:'P',name:'Part',warehouse:'A',date:'2026-10-09',received:0,issued:4}];const r=calculate(report('stock-balance'),raw,{from:'2026-10-01',to:'2026-10-08'});assert.equal(r.rows[0].opening,10);assert.equal(r.rows[0].issued,3);assert.equal(r.rows[0].closing,7);});
test('stock card search selects part, retaining all its movements and running balance',()=>{const raw=[{id:'1',partId:'p',partCode:'P',name:'Lọc dầu',warehouse:'A',date:'2026-09-01',received:10,issued:0},{id:'2',partId:'p',partCode:'P',name:'Lọc dầu',warehouse:'A',date:'2026-10-01',received:0,issued:3},{id:'3',partId:'p',partCode:'P',name:'Lọc dầu',warehouse:'A',date:'2026-10-02',received:2,issued:0}];const r=calculate(report('stock-card'),raw,{from:'2026-10-01',to:'2026-10-08',q:'Lọc dầu'});assert.deepEqual(r.rows.map(r=>r.closing),[7,9]);});
test('bank running balance is isolated per account and includes configured opening',()=>{const raw=[{id:'1',date:'2026-09-30',method:'Chuyển khoản',accountId:'a',account:'A',income:50,expense:0},{id:'2',date:'2026-10-01',method:'Chuyển khoản',accountId:'a',account:'A',income:20,expense:0},{id:'3',date:'2026-10-02',method:'Chuyển khoản',accountId:'b',account:'B',income:0,expense:10}];raw.openingAccounts=[{id:'a',name:'A',amount:100},{id:'b',name:'B',amount:200}];const r=calculate(report('bankbook'),raw,{from:'2026-10-01',to:'2026-10-08'});assert.deepEqual(r.rows.map(r=>r.closing),[170,190]);assert.equal(r.meta.opening,350);assert.equal(r.meta.closing,360);});
test('one job with multiple allocations is counted once for each technician',()=>{const raw=[{id:'1',employee:'A',TLENHSUACHUAID:'job',date:'2026-10-01'},{id:'2',employee:'A',TLENHSUACHUAID:'job',date:'2026-10-01'},{id:'3',employee:'B',TLENHSUACHUAID:'job',date:'2026-10-01'}];const r=calculate(report('staff-productivity'),raw,{});assert.equal(r.rows.find(r=>r.name==='A').jobs,1);assert.equal(r.rows.find(r=>r.name==='B').jobs,1);});
test('same-name customers retain separate identities in aggregates',()=>{const r=calculate(report('revenue-customer'),[{id:'1',partner:'Trùng tên',partnerKey:'a',amount:10},{id:'2',partner:'Trùng tên',partnerKey:'b',amount:20}],{});assert.equal(r.rows.length,2);assert.equal(r.totals.amount,30);});
test('total productivity counts unique jobs across technicians',()=>{const r=calculate(report('staff-productivity'),[{id:'1',employee:'A',TLENHSUACHUAID:'job'},{id:'2',employee:'B',TLENHSUACHUAID:'job'}],{});assert.equal(r.totals.jobs,1);});
test('snapshot routes hide raw fields, prevent theft, and re-check rights on export',async()=>{
 const express=require('express'),service=require('../src/services/reportData');const original=service.run;const app=express();app.use((req,res,next)=>{req.accessUser={ID:req.headers['x-user']||'owner',permissions:{REPORTS:Number(req.headers['x-rights']||17)}};next();});app.use(require('../src/routes/reportCenter'));
 service.run=async()=>({report:report('receipts'),rows:[{id:'a',code:'PT',income:100,SECRET:'hidden'}],notes:[],filters:{},totals:{income:100},options:{},meta:{},createdAt:'2026-10-08'});
 const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));const url=`http://127.0.0.1:${server.address().port}`;
 try{const run=await fetch(url+'/run/receipts');const body=await run.json();assert.equal(run.status,200);const rows=await (await fetch(url+'/snapshots/'+body.snapshot+'/rows')).json();assert.equal(rows.data[0].SECRET,undefined);assert.equal((await fetch(url+'/snapshots/'+body.snapshot+'/rows',{headers:{'x-user':'thief'}})).status,410);assert.equal((await fetch(url+'/snapshots/'+body.snapshot+'/excel',{headers:{'x-rights':'1'}})).status,403);assert.equal((await fetch(url+'/snapshots/'+body.snapshot+'/rows?page=0')).status,400);assert.equal((await fetch(url+'/snapshots/'+body.snapshot+'/excel')).status,200);
 }finally{service.run=original;await new Promise(resolve=>server.close(resolve));}
});
test('snapshot total covers the full report, not only the first 50 rows',()=>{const raw=Array.from({length:125},(_,i)=>({id:String(i),date:'2026-10-01',source:'Sửa chữa',amount:10,paid:4,remaining:6}));const r=calculate(report('repair-invoices'),raw,{});assert.equal(r.rows.length,125);assert.equal(r.totals.amount,1250);});
test('XLSX is a ZIP container with inline strings, preserving formula-like text as text',()=>{const result={report:report('receipts'),createdAt:'2026-10-08',filters:{},notes:[],rows:[{code:'=1+1',income:100}],totals:{income:100}};const b=xlsx(result);assert.equal(b.readUInt32LE(0),0x04034b50);assert.ok(b.includes(Buffer.from('t="inlineStr"')));assert.ok(b.includes(Buffer.from('=1+1')));assert.equal(crc32(Buffer.from('123456789')),0xcbf43926);});
test('print payload preserves row numbers and treats company/filter/data text as literal content',()=>{
 const {buildPrintTemplate}=require('../src/services/reportExport');
 const result={report:report('receipts'),createdAt:'2026-10-07T18:00:00Z',filters:{from:'2026-10-01',to:'2026-10-08',partner:'[x] & <test>'},notes:[],rows:[{code:'[not an expression]',income:150}],totals:{income:150}};
 const {template,tables}=buildPrintTemplate(result,'portrait',{name:'Garage <A> [B]',address:'',phone:'',email:''});
 assert.equal(tables.Rows[0].C0,'1');assert.equal(tables.Rows[0].C1,'[not an expression]');assert.equal(tables.Rows[0].C7,'150');
 assert.ok(template.includes('Garage &lt;A&gt; [B]'));assert.ok(template.includes('Ngày 08 tháng 10 năm 2026'));assert.ok(template.includes('Text="Khách hàng / NCC: [x] &amp; &lt;test&gt;"'));
 assert.ok(template.includes('Name="CompanyName"'));assert.ok(template.includes('AllowExpressions="false"'));assert.ok(template.includes('ColSpan="7"'));
});
