const sizes={ 'A4-doc':{width:210,height:297,margin:10},'A4-ngang':{width:297,height:210,margin:10},A5:{width:148,height:210,margin:7},'80mm':{width:80,height:297,margin:0} };
const esc=value=>String(value).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');
function styled(type,size){
 const paper=sizes[size];if(!paper)throw Error('Khổ giấy không hợp lệ');
 const receipt=size==='80mm',a5=size==='A5',w=receipt?272.16:Math.round((paper.width-2*paper.margin)*3.78*100)/100;
 const font=receipt?8:a5?9:10,rh=receipt?20:a5?24:28;
 const descriptive=type.layout==='text'&&type.key!=='MauPhieuBanGiao',barcode=type.layout==='barcode',money=!descriptive&&!barcode,cash=['MauPhieuThu','MauPhieuChi'].includes(type.key);
 let n=0;
 const text=(value,x,y,width,height,extra='',f=font)=>`<TextObject Name="StyledText${++n}" Left="${x}" Top="${y}" Width="${width}" Height="${height}" Text="${esc(value)}" Font="Arial, ${f}pt${extra.includes('Font.Style="Bold"')?', style=Bold':extra.includes('Font.Style="Italic"')?', style=Italic':''}" CanGrow="true" ShiftMode="WhenOverlapped" ${extra.replace(/Font.Style="[^"]*"/g,'')}/>`;
 const bold='Font.Style="Bold"';
 const strings=['CompanyName','CompanyAddress','CompanyPhone','CompanyEmail','DocTitle','DocNumber','DocDate','CustomerName','Contact','VehiclePlate','Description','Extra','FooterNote','In bởi','DKHACHHANG_DIACHI'];
 const numbers=['TIENHANG','TIENGIAMGIA','TILEGIAMGIA','TIENTHUE','TILETHUE','PHIDICHVU','PHIVANCHUYEN','TONGCONG'];
 const fields=['Index','ItemName','ItemCode','Unit','QuantityText','UnitPriceText','AmountText','ValueText','Note','BARCODE'];
 const dictionary=`<Dictionary><TableDataSource Name="Table0" ReferenceName="Data.Table0" DataType="System.Int32" Enabled="true">${fields.map(f=>`<Column Name="${f}" DataType="System.String"/>`).join('')}<Column Name="SOLUONG" DataType="System.Decimal"/></TableDataSource>${strings.map(p=>`<Parameter Name="${p}" DataType="System.String"/>`).join('')}${numbers.map(p=>`<Parameter Name="${p}" DataType="System.Decimal"/>`).join('')}<Total Name="StyledTotalQuantity" Expression="[Table0.SOLUONG]" Evaluator="Data1" PrintOn="ReportSummary1"/></Dictionary>`;
 let header='',height;
 if(receipt){
  header='<PictureObject Name="CompanyLogo" Left="4" Width="48" Height="52" SizeMode="Zoom"/>'+text('[CompanyName]',56,0,w-56,21,`${bold} HorzAlign="Center"`,11)+text('[CompanyAddress]',56,23,w-56,30,'HorzAlign="Center"',7)+text('[CompanyPhone]',0,57,w,18,'HorzAlign="Center"')+text('[DocTitle]',0,80,w,30,`${bold} HorzAlign="Center"`,13)+text('Ngày: [DocDate]',0,113,w*.45,19)+text('Số: [DocNumber]',w*.45,113,w*.55,19,'HorzAlign="Right"')+text('Nhân viên: [In bởi]',0,135,w,19)+text('Khách hàng: [CustomerName]',0,156,w,19)+text('Xe: [VehiclePlate]   ĐT: [Contact]',0,177,w,19)+text('[Description]',0,198,w,16,'CanShrink="true" VisibleExpression="[Description] != &quot;&quot;"',7);height=218;
 }else if(a5){
  header=text('Đơn vị: [CompanyName]',0,0,w*.51,24,bold,10)+text('Địa chỉ: [CompanyAddress]',0,27,w*.51,36)+text('Điện thoại: [CompanyPhone]',0,66,w*.51,24)+text('[DocTitle]',w*.53,8,w*.47,40,`${bold} HorzAlign="Center"`,13)+text('Ngày [DocDate]',w*.53,50,w*.47,22,'HorzAlign="Center"')+text('Số: [DocNumber]',w*.53,75,w*.47,25,`${bold} HorzAlign="Center"`,10)+text('Khách hàng: [CustomerName]',0,111,w*.64,24)+text('Nhân viên: [In bởi]',w*.65,111,w*.35,24,'HorzAlign="Right"')+text('Địa chỉ: [DKHACHHANG_DIACHI]',0,137,w,24)+text('ĐT: [Contact]    Xe: [VehiclePlate]',0,163,w,24)+text('[Description]',0,189,w,20,'CanShrink="true" VisibleExpression="[Description] != &quot;&quot;"');height=212;
 }else{
  header='<PictureObject Name="CompanyLogo" Left="12" Width="85" Height="72" SizeMode="Zoom"/>'+text('[CompanyName]',105,0,w-105,27,`${bold} HorzAlign="Center"`,14)+text('Địa chỉ: [CompanyAddress]',105,30,w-105,25,'HorzAlign="Center"')+text('Điện thoại: [CompanyPhone]   Email: [CompanyEmail]',105,57,w-105,24,'HorzAlign="Center"',9)+`<LineObject Name="CompanyDivider" Top="90" Width="${w}" Border.Width="1.5"/>`+text('[DocTitle]',0,105,w,39,`${bold} HorzAlign="Center"`,20)+text('Ngày [DocDate]',0,147,w,24,'HorzAlign="Center"')+text('Khách hàng: [CustomerName]',0,177,w*.59,26,bold,11)+text('Số phiếu: [DocNumber]',w*.60,177,w*.40,26,`${bold} HorzAlign="Right"`,11)+text('Địa chỉ: [DKHACHHANG_DIACHI]',0,206,w*.67,25)+text('Nhân viên: [In bởi]',w*.67,206,w*.33,25,'HorzAlign="Right"')+text('Điện thoại: [Contact]     Biển số xe: [VehiclePlate]',0,234,w,25)+text('[Description]',0,263,w,23,'CanShrink="true" VisibleExpression="[Description] != &quot;&quot;"');height=290;
 }
 const cols=descriptive?[['Nội dung','ItemName',w*.34],['Thông tin','ValueText',w*.66]]:barcode?[['Mã hàng','ItemCode',w*.23],['Tên phụ tùng','ItemName',w*.54],['Giá','AmountText',w*.23]]:cash?[['Nội dung','ItemName',w*.64],['Số tiền','AmountText',w*.36]]:receipt?[['STT','Index',18],['Mặt hàng','ItemName',100.16],['SL','QuantityText',28],['Giá','UnitPriceText',58],['T Tiền','AmountText',68]]:[['STT','Index',w*.06],['Tên hàng / Hạng mục','ItemName',w*.36],['ĐVT','Unit',w*.08],[a5?'SL':'S.lượng','QuantityText',w*.09],['Đơn giá','UnitPriceText',w*.19],['Thành tiền','AmountText',w*.22]];
 const table=(name,detail)=>`<TableObject Name="${name}" Width="${w}" Height="${rh}">${cols.map((c,i)=>`<TableColumn Name="${name}Column${i}" Width="${Math.round(c[2]*100)/100}"/>`).join('')}<TableRow Name="${name}Row" MinHeight="${rh}" AutoSize="true">${cols.map(([label,field],i)=>`<TableCell Name="${name}Cell${i}" Text="${esc(detail?`[Table0.${field}]`:label)}" Border.Lines="All" ${receipt?'Border.Style="Dash"':''} Padding="2, 2, 2, 2" HorzAlign="${detail?(field==='ItemName'||field==='ValueText'?'Left':['Index','Unit','QuantityText'].includes(field)?'Center':'Right'):'Center'}" VertAlign="Center" Font="Arial, ${receipt&&label==='STT'?5.5:font}pt${detail?'':', style=Bold'}" ${!detail&&receipt?'Fill.Color="255, 255, 192"':''} ${label==='STT'?'WordWrap="false"':''}/>`).join('')}</TableRow></TableObject>`;
 const detail=table('detail',true)+(barcode?`<BarcodeObject Name="Code" Top="${rh+6}" Width="${Math.min(w,260)}" Height="65" DataColumn="Table0.BARCODE" Barcode="Code128"/>`:text('[Table0.Note]',0,rh,w,15,'CanShrink="true" VisibleExpression="[Table0.Note] != &quot;&quot; &amp;&amp; [Table0.Note] != [Table0.ItemName]" Font.Style="Italic"',receipt?7:8));
 const sumrow=(id,label,field,cond='',strong=false)=>`<TableRow Name="${id}" MinHeight="${rh+2}" AutoSize="true" ${cond?`VisibleExpression="${cond}"`:''}><TableCell Name="${id}Label" Text="${esc(label)}" Font="Arial, ${font}pt${strong?', style=Bold':''}" Padding="2, 2, 2, 2"/><TableCell Name="${id}Amount" Text="[${field}]" HorzAlign="Right" Font="Arial, ${strong?(receipt?13:font+3):font}pt${strong?', style=Bold':''}" Padding="2, 2, 2, 2" Format="Number" Format.UseLocale="false" Format.DecimalDigits="0" Format.GroupSeparator=","/></TableRow>`;
 let totals=money?`<TableObject Name="StyledSummary" Width="${w}" Height="${rh*7}" Border.Lines="Top"><TableColumn Name="SummaryLabelColumn" Width="${w*.64}"/><TableColumn Name="SummaryAmountColumn" Width="${w*.36}"/>${sumrow('QuantitySummary','Tổng SL:','StyledTotalQuantity',cash?'false':'')}${sumrow('SubtotalSummary','Tiền hàng:','TIENHANG',cash?'false':'',true)}${sumrow('DiscountSummary','Giảm giá:','TIENGIAMGIA','[TIENGIAMGIA] != 0')}${sumrow('FeeSummary','Phí dịch vụ:','PHIDICHVU','[PHIDICHVU] != 0')}${sumrow('TaxSummary','VAT ([TILETHUE]%):','TIENTHUE','[TIENTHUE] != 0')}${sumrow('ShippingSummary','Vận chuyển:','PHIVANCHUYEN','[PHIVANCHUYEN] != 0')}${sumrow('GrandTotalSummary','Tổng:','TONGCONG','',true)}<TableRow Name="WordsSummary" MinHeight="${rh+8}" AutoSize="true"><TableCell Name="WordsCell" ColSpan="2" Text="[ToVndWords([TONGCONG])] đồng." Font="Arial, ${font}pt, style=Italic" Padding="2, 4, 2, 4"/><TableCell Name="WordsEmpty"/></TableRow><TableRow Name="ExtraSummary" AutoSize="true" VisibleExpression="[Extra] != &quot;&quot;"><TableCell Name="ExtraCell" ColSpan="2" Text="[Extra]" Font="Arial, ${font}pt"/><TableCell Name="ExtraEmpty"/></TableRow><TableRow Name="SignaturesSummary" Height="${receipt?38:70}"><TableCell Name="CustomerSignature" Text="Khách hàng / người giao nhận" HorzAlign="Center" Font="Arial, ${font}pt, style=Bold"/><TableCell Name="StaffSignature" Text="Nhân viên GARA" HorzAlign="Center" Font="Arial, ${font}pt, style=Bold"/></TableRow>${receipt?'<TableRow Name="ThanksSummary" Height="23"><TableCell Name="ThanksCell" ColSpan="2" Text="Cảm ơn quý khách và hẹn gặp lại!" HorzAlign="Center" Font="Arial, 7pt, style=Italic"/><TableCell Name="ThanksEmpty"/></TableRow>':''}</TableObject>`:text('[Extra]',0,8,w,26,'CanShrink="true"')+text('[FooterNote]',0,42,w,36,'HorzAlign="Center"');
 if(money&&!receipt){
  const summaryWidth=Math.round(Math.min(420,w*.56)*100)/100;
  const split=totals.indexOf('<TableRow Name="WordsSummary"');
  const financial=totals.slice(0,split);
  const footer=totals.slice(split);
  const nominal=7*(rh+2);
  totals=financial.replace('Name="StyledSummary" Width="'+w+'" Height="'+(rh*7)+'"','Name="StyledSummary" Left="'+(w-summaryWidth)+'" Width="'+summaryWidth+'" Height="'+nominal+'"')
   .replace('Name="SummaryLabelColumn" Width="'+(w*.64)+'"','Name="SummaryLabelColumn" Width="'+(summaryWidth*.56)+'"')
   .replace('Name="SummaryAmountColumn" Width="'+(w*.36)+'"','Name="SummaryAmountColumn" Width="'+(summaryWidth*.44)+'"')
   .replace('Name="GrandTotalSummaryLabel"','Name="GrandTotalSummaryLabel" Border.Lines="Top"')
   .replace('Name="GrandTotalSummaryAmount"','Name="GrandTotalSummaryAmount" Border.Lines="Top"')+'</TableObject>'+
   '<TableObject Name="StyledFooter" Left="0" Top="'+nominal+'" Width="'+w+'" Height="'+(rh*4)+'" ShiftMode="Always"><TableColumn Name="FooterLeftColumn" Width="'+(w*.5)+'"/><TableColumn Name="FooterRightColumn" Width="'+(w*.5)+'"/>'+footer;
 }
 return `<?xml version="1.0" encoding="utf-8"?><Report DoublePass="true" ScriptLanguage="CSharp" ReportInfo.Description="Phong cách hóa đơn bán phụ tùng">${dictionary}<ReportPage Name="Page1" PaperWidth="${paper.width}" PaperHeight="${paper.height}" LeftMargin="${paper.margin}" RightMargin="${receipt?8:paper.margin}" TopMargin="${receipt?3:paper.margin}" BottomMargin="${receipt?3:paper.margin}"><ReportTitleBand Name="Title" Width="${w}" Height="${height}" CanGrow="true" CanShrink="true">${header}</ReportTitleBand><DataBand Name="Data1" Width="${w}" Height="${barcode?rh+76:rh}" DataSource="Table0" CanGrow="true" CanShrink="true">${detail}<DataHeaderBand Name="Columns" Width="${w}" Height="${rh}" CanGrow="true" RepeatOnEveryPage="true">${table('colHeader',false)}</DataHeaderBand></DataBand><ReportSummaryBand Name="ReportSummary1" Width="${w}" Height="${money?rh*7:80}" CanGrow="true" CanShrink="true">${totals}</ReportSummaryBand>${receipt?'':`<PageFooterBand Name="Footer" Width="${w}" Height="20">${text('Trang [Page]',0,0,w,20,'HorzAlign="Right"',8)}</PageFooterBand>`}</ReportPage></Report>`;
}
module.exports={sizes,build:styled};




