const crypto=require('crypto'), db=require('../db'), printing=require('./documentPrint');
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const fail=(message,status=400)=>Object.assign(new Error(message),{status});
const admin=user=>{if(Number(user?.ISADMIN)!==1)throw fail('Chỉ Admin được cấu hình Agent.',403);};
const jobFields='ID,USERID,TYPEKEY,RECORDID,TEMPLATEID,PRINTERID,STATIONID,PRINTERNAME,WIDTHMM,COPIES,STATE,PDFHASH,CREATED,EXPIRES,DETAIL';
async function event(q,id,state,detail=''){await q('INSERT INTO PRINT_JOB_EVENTS (ID,JOBID,STATE,DETAIL) VALUES (?,?,?,?)',[crypto.randomUUID(),id,state,String(detail).slice(0,500)]);}
function canRead(user,job){return Number(user.ISADMIN)===1 || job.USERID===user.ID;}
async function pairing(user){admin(user);const ticket=crypto.randomBytes(24).toString('base64url');await db.execute('INSERT INTO PRINT_PAIRINGS (ID,TICKETHASH,EXPIRES) VALUES (?,?,DATEADD(5 MINUTE TO CURRENT_TIMESTAMP))',[crypto.randomUUID(),hash(ticket)]);return {ticket,expiresIn:300};}
async function pair(ticket,name){if(typeof ticket!=='string'||ticket.length>100)throw fail('Mã ghép không hợp lệ.');const token=crypto.randomBytes(32).toString('base64url'),id=crypto.randomUUID();await db.transaction(async(q,x)=>{const [row]=await q('SELECT ID FROM PRINT_PAIRINGS WHERE TICKETHASH=? AND USED=0 AND EXPIRES>CURRENT_TIMESTAMP WITH LOCK',[hash(ticket)]);if(!row)throw fail('Mã ghép hết hạn hoặc đã dùng.',403);await x('UPDATE PRINT_PAIRINGS SET USED=1 WHERE ID=?',[row.ID]);await x('INSERT INTO PRINT_STATIONS (ID,NAME,TOKENHASH,LASTSEEN) VALUES (?,?,?,CURRENT_TIMESTAMP)',[id,String(name||'Máy GARA').slice(0,120),hash(token)]);});return {stationId:id,token};}
async function authenticate(token){if(!token||token.length>100)throw fail('Thiếu credential Agent.',401);const [station]=await db.query('SELECT ID,NAME FROM PRINT_STATIONS WHERE TOKENHASH=? AND REVOKED=0',[hash(token)]);if(!station)throw fail('Agent chưa ghép hoặc đã thu hồi.',401);return station;}
async function heartbeat(station,body){await db.transaction(async(q,x)=>{await x('UPDATE PRINT_STATIONS SET LASTSEEN=CURRENT_TIMESTAMP,VERSION=? WHERE ID=?',[String(body.version||'').slice(0,40),station.ID]);const names=[...new Set((body.printers||[]).slice(0,100).map(p=>String(p.name||'').trim().slice(0,200)).filter(Boolean))];for(const name of names){if(!(await q('SELECT ID FROM PRINT_PRINTERS WHERE STATIONID=? AND NAME=?',[station.ID,name])).length)await x('INSERT INTO PRINT_PRINTERS (ID,STATIONID,NAME) VALUES (?,?,?)',[crypto.randomUUID(),station.ID,name]);}const known=await q('SELECT ID,NAME FROM PRINT_PRINTERS WHERE STATIONID=?',[station.ID]);for(const printer of known)if(!names.includes(printer.NAME))await x('UPDATE PRINT_PRINTERS SET ENABLED=0 WHERE ID=?',[printer.ID]);});return {ok:true};}
async function configuration(){const stations=await db.query('SELECT ID,NAME,LASTSEEN,REVOKED,VERSION,CASE WHEN LASTSEEN>DATEADD(-90 SECOND TO CURRENT_TIMESTAMP) AND REVOKED=0 THEN 1 ELSE 0 END AS ONLINE FROM PRINT_STATIONS');const printers=await db.query('SELECT P.*,S.NAME AS STATIONNAME,CASE WHEN S.LASTSEEN>DATEADD(-90 SECOND TO CURRENT_TIMESTAMP) AND S.REVOKED=0 THEN 1 ELSE 0 END AS ONLINE FROM PRINT_PRINTERS P JOIN PRINT_STATIONS S ON S.ID=P.STATIONID');return {stations,printers,routes:await db.query('SELECT TYPEKEY,PRINTERID FROM PRINT_ROUTES')};}
async function configure(user,id,body){admin(user);const width=Number(body.widthMm);if(![0,54,58,80,210,148].includes(width))throw fail('Khổ giấy không hợp lệ.');await db.transaction(async(q,x)=>{if(!(await q('SELECT ID FROM PRINT_PRINTERS WHERE ID=?',[id])).length)throw fail('Không có máy in.',404);await x('UPDATE PRINT_PRINTERS SET ENABLED=?,WIDTHMM=? WHERE ID=?',[body.enabled?1:0,width,id]);if(!body.enabled){const jobs=await q("SELECT ID FROM PRINT_JOBS WHERE PRINTERID=? AND STATE IN ('queued','received') WITH LOCK",[id]);for(const j of jobs){await x("UPDATE PRINT_JOBS SET STATE='cancelled',DETAIL='Máy in đã tắt' WHERE ID=?",[j.ID]);await event(x,j.ID,'cancelled','Máy in đã tắt');}}if(body.types){for(const key of body.types){printing.typeByKey(key);await x('UPDATE OR INSERT INTO PRINT_ROUTES (TYPEKEY,PRINTERID) VALUES (?,?) MATCHING (TYPEKEY)',[key,id]);}}});return {ok:true};}
async function revoke(user,id){admin(user);await db.transaction(async(q,x)=>{await x('UPDATE PRINT_STATIONS SET REVOKED=1,TOKENHASH=NULL WHERE ID=?',[id]);const rows=await q("SELECT ID FROM PRINT_JOBS WHERE STATIONID=? AND STATE IN ('queued','received') WITH LOCK",[id]);for(const row of rows){await x("UPDATE PRINT_JOBS SET STATE='cancelled',DETAIL='Trạm đã thu hồi' WHERE ID=?",[row.ID]);await event(x,row.ID,'cancelled','Trạm đã thu hồi');}});return {ok:true};}
async function getJob(user,id){const [job]=await db.query(`SELECT ${jobFields} FROM PRINT_JOBS WHERE ID=?`,[id]);if(!job||!canRead(user,job)||!printing.permitted(user,printing.typeByKey(job.TYPEKEY)))throw fail('Không tìm thấy lệnh in.',404);return {...job,events:await db.query('SELECT STATE,DETAIL,CREATED FROM PRINT_JOB_EVENTS WHERE JOBID=? ORDER BY CREATED',[id])};}
async function createJob(user,body){const type=printing.typeByKey(body.type);if(!printing.permitted(user,type))throw fail('Bạn cần quyền Xem và In.',403);const key=String(body.idempotencyKey||'');if(!/^[a-zA-Z0-9_-]{16,80}$/.test(key))throw fail('Thiếu khóa chống gửi trùng.');const copies=Number(body.copies||1);if(!Number.isInteger(copies)||copies<1||copies>5)throw fail('Số bản phải từ 1 đến 5.');const [existing]=await db.query(`SELECT ${jobFields} FROM PRINT_JOBS WHERE USERID=? AND IDEMKEY=?`,[user.ID,key]);if(existing)return existing;
const [printer]=await db.query(`SELECT P.*,S.REVOKED,CASE WHEN S.LASTSEEN>DATEADD(-90 SECOND TO CURRENT_TIMESTAMP) THEN 1 ELSE 0 END AS ONLINE FROM PRINT_PRINTERS P JOIN PRINT_STATIONS S ON S.ID=P.STATIONID WHERE P.ID=COALESCE(?,(SELECT PRINTERID FROM PRINT_ROUTES WHERE TYPEKEY=?))`,[body.printerId||null,type.key]);if(!printer)throw fail('Chưa cấu hình máy in mặc định. Admin hãy ghép Agent và chọn máy in.');if(!printer.ENABLED||printer.REVOKED||!printer.ONLINE)throw fail('Máy in đã tắt hoặc Agent mất kết nối.',409);
const rendered=await printing.render(type,String(body.recordId||''),{templateId:body.templateId,from:body.from,to:body.to},user.USERNAME);const id=crypto.randomUUID();try{await db.transaction(async(q,x)=>{const [active]=await q('SELECT P.ENABLED,S.REVOKED,S.LASTSEEN FROM PRINT_PRINTERS P JOIN PRINT_STATIONS S ON S.ID=P.STATIONID WHERE P.ID=?',[printer.ID]);if(!active?.ENABLED||active.REVOKED||Date.now()-new Date(active.LASTSEEN).getTime()>90000)throw fail('Agent vừa mất kết nối hoặc máy in đã tắt.',409);await x(`INSERT INTO PRINT_JOBS (ID,USERID,TYPEKEY,RECORDID,TEMPLATEID,PRINTERID,STATIONID,PRINTERNAME,WIDTHMM,COPIES,STATE,IDEMKEY,PDFHASH,EXPIRES,PDFDATA) VALUES (?,?,?,?,?,?,?,?,?,?,'queued',?,?,DATEADD(5 MINUTE TO CURRENT_TIMESTAMP),?)`,[id,user.ID,type.key,String(body.recordId),rendered.template.ID,printer.ID,printer.STATIONID,printer.NAME,printer.WIDTHMM,copies,key,hash(rendered.pdf),rendered.pdf]);await event(x,id,'queued');});}catch(e){const [duplicate]=await db.query(`SELECT ${jobFields} FROM PRINT_JOBS WHERE USERID=? AND IDEMKEY=?`,[user.ID,key]);if(duplicate)return duplicate;throw e;}return getJob(user,id);}
async function claim(station){return db.transaction(async(q,x)=>{await x("UPDATE PRINT_JOBS SET STATE='expired',DETAIL='Hết hạn chờ trạm' WHERE STATIONID=? AND STATE='queued' AND EXPIRES<CURRENT_TIMESTAMP",[station.ID]);await x("UPDATE PRINT_JOBS SET STATE='needs_review',DETAIL='Mất kết nối trong lúc gửi; kiểm tra giấy trước khi in lại' WHERE STATIONID=? AND STATE='dispatching' AND LEASEUNTIL<CURRENT_TIMESTAMP",[station.ID]);const [job]=await q(`SELECT FIRST 1 ${jobFields} FROM PRINT_JOBS WHERE STATIONID=? AND EXPIRES>CURRENT_TIMESTAMP AND (STATE='queued' OR (STATE='received' AND LEASEUNTIL<CURRENT_TIMESTAMP)) ORDER BY CREATED WITH LOCK`,[station.ID]);if(!job)return null;await x("UPDATE PRINT_JOBS SET STATE='received',LEASEUNTIL=DATEADD(120 SECOND TO CURRENT_TIMESTAMP) WHERE ID=?",[job.ID]);await event(x,job.ID,'received');return {...job,STATE:'received'};});}
async function pdf(station,id){const [job]=await db.query('SELECT STATE FROM PRINT_JOBS WHERE ID=? AND STATIONID=?',[id,station.ID]);if(!job||!['received','dispatching','needs_review'].includes(job.STATE))throw fail('Lệnh không thuộc trạm hoặc đã kết thúc.',404);return db.queryBlob('SELECT PDFDATA FROM PRINT_JOBS WHERE ID=?',[id],'PDFDATA');}
async function report(station,id,body){const state=body.state;if(!['dispatching','submitted','failed','needs_review'].includes(state))throw fail('Trạng thái không hợp lệ.');await db.transaction(async(q,x)=>{const [j]=await q('SELECT STATE FROM PRINT_JOBS WHERE ID=? AND STATIONID=? WITH LOCK',[id,station.ID]);if(!j)throw fail('Không có lệnh.',404);if(j.STATE===state)return;if(state==='dispatching'&&j.STATE!=='received')throw fail('Lệnh đã hủy hoặc không còn được phép gửi.',409);if(state!=='dispatching'&&!['received','dispatching','needs_review'].includes(j.STATE))throw fail('Lệnh đã kết thúc.',409);await x('UPDATE PRINT_JOBS SET STATE=?,DETAIL=?,LEASEUNTIL=DATEADD(180 SECOND TO CURRENT_TIMESTAMP) WHERE ID=?',[state,String(body.detail||'').slice(0,500),id]);await event(x,id,state,body.detail);});return {ok:true};}
async function cancel(user,id){await getJob(user,id);await db.transaction(async(q,x)=>{const [j]=await q('SELECT STATE FROM PRINT_JOBS WHERE ID=? WITH LOCK',[id]);if(!['queued','received'].includes(j.STATE))throw fail('Lệnh đã bắt đầu gửi; không thể hủy tại đây.',409);await x("UPDATE PRINT_JOBS SET STATE='cancelled' WHERE ID=?",[id]);await event(x,id,'cancelled');});return {ok:true};}
async function reprint(user,id,key){const old=await getJob(user,id);if(!['submitted','failed','needs_review','cancelled','expired'].includes(old.STATE))throw fail('Lệnh cũ chưa kết thúc.',409);if(!/^[a-zA-Z0-9_-]{16,80}$/.test(String(key||'')))throw fail('Thiếu khóa chống gửi trùng.');const [duplicate]=await db.query(`SELECT ${jobFields} FROM PRINT_JOBS WHERE USERID=? AND IDEMKEY=?`,[user.ID,key]);if(duplicate)return duplicate;const [ready]=await db.query('SELECT P.ID FROM PRINT_PRINTERS P JOIN PRINT_STATIONS S ON S.ID=P.STATIONID WHERE P.ID=? AND P.ENABLED=1 AND S.REVOKED=0 AND S.LASTSEEN>DATEADD(-90 SECOND TO CURRENT_TIMESTAMP)',[old.PRINTERID]);if(!ready)throw fail('Máy in tắt hoặc Agent mất kết nối.',409);const bytes=await db.queryBlob('SELECT PDFDATA FROM PRINT_JOBS WHERE ID=?',[id],'PDFDATA');if(!bytes)throw fail('PDF đã hết thời hạn lưu. Hãy tạo bản in mới từ chứng từ.',410);const next=crypto.randomUUID();try{await db.transaction(async(q,x)=>{await x("INSERT INTO PRINT_JOBS (ID,USERID,TYPEKEY,RECORDID,TEMPLATEID,PRINTERID,STATIONID,PRINTERNAME,WIDTHMM,COPIES,STATE,IDEMKEY,PDFHASH,EXPIRES,PDFDATA) VALUES (?,?,?,?,?,?,?,?,?,?,'queued',?,?,DATEADD(5 MINUTE TO CURRENT_TIMESTAMP),?)",[next,user.ID,old.TYPEKEY,old.RECORDID,old.TEMPLATEID,old.PRINTERID,old.STATIONID,old.PRINTERNAME,old.WIDTHMM,old.COPIES,key,old.PDFHASH,bytes]);await event(x,next,'queued','In lại bản PDF của lệnh '+id);});}catch(e){const [row]=await db.query(`SELECT ${jobFields} FROM PRINT_JOBS WHERE USERID=? AND IDEMKEY=?`,[user.ID,key]);if(row)return row;throw e;}return getJob(user,next);}
async function maintenance(){await db.execute("UPDATE PRINT_JOBS SET PDFDATA=NULL WHERE CREATED<DATEADD(-7 DAY TO CURRENT_TIMESTAMP) AND STATE NOT IN ('queued','received','dispatching') AND PDFDATA IS NOT NULL");}
module.exports={pairing,pair,authenticate,heartbeat,configuration,configure,revoke,getJob,createJob,claim,pdf,report,cancel,reprint,maintenance,hash};
