const db=require('../db');
const {reports,permitted}=require('./reportCatalog');
const {dateRange}=require('./employeeCommissions');
const fail=(message,status=400)=>Object.assign(new Error(message),{status});
const round=x=>Math.round((Number(x)||0)*100)/100;
const day=x=>!x?'':typeof x==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(x)?x:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(x));
const today=()=>day(new Date());
function validate(input={}){const range=dateRange(input);const f={...range};for(const k of ['q','partner','plate','employee','warehouse','status','account','method']){f[k]=String(input[k]||'').trim();if(f[k].length>120)throw fail('Bộ lọc quá dài.');}f.days=Number(input.days||90);if(!Number.isInteger(f.days)||f.days<1||f.days>3650)throw fail('Số ngày phải từ 1 đến 3650.');return f;}
const fields={
 DKHACHHANG:'ID NAME MAKHACH DNHOMKHACHHANGID DIENTHOAI DIACHI',DNHACUNGCAP:'ID NAME MANHACUNGCAP DNHOMNHACUNGCAPID DIENTHOAI DIACHI',DXE:'ID BIENSO NAME DKHACHHANGID ODO',DNHANVIEN:'ID CODE NAME DIENTHOAI STATUS',
 DMATHANG:'ID CODE NAME MAOEM DNHOMMATHANGID DDONVITINHID DVITRIKHOID GIANHAP GIABAN TONTOITHIEU',DDICHVU:'ID CODE NAME DLOAIDICHVUID GIA',DVITRIKHO:'ID NAME DKHOHANGID',DKHOHANG:'ID NAME',DNHOMMATHANG:'ID NAME',DNHOMKHACHHANG:'ID NAME',DNHOMNHACUNGCAP:'ID NAME',DLOAIDICHVU:'ID NAME',DDONVITINH:'ID NAME',DLYDOTHUCHI:'ID NAME',DTAIKHOANNGANHANG:'ID NAME SODUDAU',
 TTHUCHI:'ID NAME NGAY DKHACHHANGID DNHACUNGCAPID DNHANVIENID DLYDOTHUCHID SOTIEN LOAI DTAIKHOANNGANHANGID TENDOITUONG NOTE CHUNGTUGOC',
 THOADONSUACHUA:'ID NAME NGAY DXEID DKHACHHANGID TLENHSUACHUAID TIENPHUTUNG TIENCONG TIENDICHVU TIENGIAMGIA TIENTHUE PHIDICHVU TONGCONG CONLAI CONGNO TIENMAT CHUYENKHOAN THE DATHANHTOAN',
 TDONHANG:'ID NAME NGAY DKHACHHANGID TIENHANG TIENGIAMGIA TIENTHUE PHIDICHVU TONGCONG CONLAI CONGNO TIENTHANHTOAN TIENMAT CHUYENKHOAN THE DATHANHTOAN LOAI DKHOXUATID',
 TDONHANGCHITIET:'ID TDONHANGID DMATHANGID SLNHAP SLXUAT DDONVITINHID DKHOHANGID DONGIA THANHTIEN',TNHAPKHO:'ID NAME NGAY DNHACUNGCAPID DKHOHANGID',TNHAPKHOCHITIET:'ID TNHAPKHOID DMATHANGID DDONVITINHID DKHOHANGID SOLUONG DONGIA THANHTIEN',
 TXUATPHUTUNG:'ID TLENHSUACHUAID DXEID DMATHANGID DKHOHANGID SOLUONG DONGIA THANHTIEN NGAYXUAT SLHOAN',
 TLENHSUACHUA:'ID NAME NGAY DXEID DKHACHHANGID BATDAU KETTHUC TRANGTHAI TONGCONG',TLENHSUACHUACHITIET:'ID TLENHSUACHUAID DDICHVUID SOLUONG DONGIA THANHTIEN',
 TTIEPNHANXE:'ID NAME NGAY DXEID DKHACHHANGID DNHANVIENCOOVANID ODO TRANGTHAI',TBAOGIA:'ID NAME NGAY DXEID DKHACHHANGID TONGCONG NGAYDUYET',TPHATSINHSUACHUA:'ID TLENHSUACHUAID TIMECREATED LYDO TRANGTHAI',
 TTRANGTHAIXE:'ID TLENHSUACHUAID DXEID DKHACHHANGID DNHANVIENKTVID NGAY_VAO NGAY_TRANGTHAI NGAY_DUKIEN TRANGTHAI',TWORKFLOWMAP:'ID STT_WORKFLOW TEN',
 TBAOHANH:'ID NAME NGAYBATDAU NGAYKETTHUC DXEID DKHACHHANGID DMATHANGID DDICHVUID TRANGTHAI KETQUAXULY CHIPHI',TLICHSUBAODUONG:'ID NAME DXEID DKHACHHANGID LOAIBAODUONG NGAY_LANCUOI NGAY_DUKIEN ODO_DUKIEN',
 TCHITIETTHANHTOAN:'ID TDONHANGID THOADONSUACHUAID NGAY SOTIEN LOAI DTAIKHOANNGANHANGID',
};
function reader(query,filters={},source=''){
 const cache={};return async(t,lookup=false)=>{
  const key=t+lookup;if(!fields[t])throw fail('Nguồn không được phép.',500);
  let condition=t==='TPHATSINHSUACHUA'?'1=1':`STATUS${lookup?'>=0':'=1'}`;
  const dateField={THOADONSUACHUA:'NGAY',TDONHANG:'NGAY',TTHUCHI:'NGAY',TLENHSUACHUA:'NGAY',TTIEPNHANXE:'NGAY',TBAOGIA:'NGAY',TPHATSINHSUACHUA:'TIMECREATED',TCHITIETTHANHTOAN:'NGAY'}[t];
  const periodSources=['invoices','repairInvoices','saleInvoices','receipts','payments','vouchers','repairs','receptions','quotes','supplements','paymentDetails','repairServices'];
  const params=[];
  if(!lookup && dateField && periodSources.includes(source)){
   if(filters.from){condition+=` AND CAST(${dateField} AS DATE)>=?`;params.push(filters.from);}
   if(filters.to){condition+=` AND CAST(${dateField} AS DATE)<=?`;params.push(filters.to);}
  }
  if(!cache[key])cache[key]=(async()=>{
   const rows=[];let offset=0;
   while(true){const page=await query(`SELECT FIRST 2000 SKIP ${offset} ${fields[t].split(' ').join(',')} FROM ${t} WHERE ${condition} ORDER BY ID`,params);rows.push(...page);if(page.length<2000)break;offset+=page.length;if(offset>500000)throw fail('Nguồn quá lớn; cần thu hẹp phạm vi dữ liệu.',413);}
   return rows;
  })();return cache[key];
 };
}
async function sources(source,f,query=db.query){
 const read=reader(query,f,source);const maps={};const map=async t=>maps[t]||(maps[t]=new Map((await read(t,true)).map(r=>[r.ID,r])));const label=async(t,id)=> (await map(t)).get(id)?.NAME||'';
 async function normalize(t){const rows=await read(t);const result=[];for(const r of rows){const car=r.DXEID?(await map('DXE')).get(r.DXEID):null;result.push({...r,id:r.ID,code:r.NAME||r.CODE||'',date:day(r.NGAY||r.NGAYBATDAU||r.TIMECREATED),name:r.NAME||'',plate:car?.BIENSO||r.BIENSO||'',partner:await label(r.DNHACUNGCAPID?'DNHACUNGCAP':'DKHACHHANG',r.DNHACUNGCAPID||r.DKHACHHANGID),partnerKey:r.DNHACUNGCAPID||r.DKHACHHANGID,plateKey:r.DXEID||r.BIENSO,employeeKey:r.DNHANVIENID||r.DNHANVIENKTVID||r.DNHANVIENCOOVANID,employee:await label('DNHANVIEN',r.DNHANVIENID||r.DNHANVIENKTVID||r.DNHANVIENCOOVANID),warehouse:await label('DKHOHANG',r.DKHOHANGID),status:String(r.TRANGTHAI??''),amount:round(r.TONGCONG),start:day(r.BATDAU),end:day(r.KETTHUC),odo:r.ODO});}return result;}
 const invoices=async(kind)=>{const table=kind==='repairInvoices'?'THOADONSUACHUA':'TDONHANG';return (await normalize(table)).filter(r=>table!=='TDONHANG'||Number(r.LOAI)===0).map(r=>{const amount=round(r.TONGCONG);const storedRemaining=round(r.CONLAI??r.CONGNO??(amount-(table==='TDONHANG'?Number(r.TIENTHANHTOAN||0):Number(r.TIENMAT||0)+Number(r.CHUYENKHOAN||0)+Number(r.THE||0))));const remaining=Number(r.DATHANHTOAN)===1?Math.min(0,storedRemaining):storedRemaining;return {...r,source:table==='TDONHANG'?'Bán phụ tùng':'Sửa chữa',subtotal:round(r.TIENHANG??Number(r.TIENPHUTUNG||0)+Number(r.TIENCONG||0)+Number(r.TIENDICHVU||0)),discount:round(r.TIENGIAMGIA),tax:round(r.TIENTHUE),fee:round(r.PHIDICHVU),paid:round(amount-remaining),remaining};});};
 if(source==='invoices')return [...await invoices('repairInvoices'),...await invoices('saleInvoices')];
 if(['repairInvoices','saleInvoices'].includes(source))return invoices(source);
 if(['customers','suppliers','cars','parts','services','employees','locations'].includes(source)){
  const table={customers:'DKHACHHANG',suppliers:'DNHACUNGCAP',cars:'DXE',parts:'DMATHANG',services:'DDICHVU',employees:'DNHANVIEN',locations:'DVITRIKHO'}[source];const out=[];
  for(const r of await normalize(table)){out.push({...r,code:r.CODE||r.MAKHACH||r.MANHACUNGCAP||r.BIENSO||'',phone:r.DIENTHOAI||'',address:r.DIACHI||'',oem:r.MAOEM||'',group:await label({customers:'DNHOMKHACHHANG',suppliers:'DNHOMNHACUNGCAP',parts:'DNHOMMATHANG',services:'DLOAIDICHVU'}[source]||'DNHOMMATHANG',r.DNHOMKHACHHANGID||r.DNHOMNHACUNGCAPID||r.DNHOMMATHANGID||r.DLOAIDICHVUID),unit:await label('DDONVITINH',r.DDONVITINHID),price:round(r.GIABAN??r.GIA),minimum:Number(r.TONTOITHIEU||0),warehouse:r.DVITRIKHOID?await label('DVITRIKHO',r.DVITRIKHOID):r.warehouse,status:source==='employees'?'Đang làm việc':r.status});}return out;
 }
 if(['receipts','payments','vouchers'].includes(source)){const rows=await normalize('TTHUCHI');const out=[];for(const r of rows){out.push({...r,partner:r.TENDOITUONG||r.partner,reason:await label('DLYDOTHUCHI',r.DLYDOTHUCHID),method:r.DTAIKHOANNGANHANGID?'Chuyển khoản':'Tiền mặt',account:await label('DTAIKHOANNGANHANG',r.DTAIKHOANNGANHANGID),income:Number(r.LOAI)===0?round(r.SOTIEN):0,expense:Number(r.LOAI)===1?round(r.SOTIEN):0});}return out.filter(r=>source==='receipts'?Number(r.LOAI)===0:source==='payments'?Number(r.LOAI)===1:true);}
 if(source==='cash'){const rows=(await require('./cashbook').load(query)).map(r=>({...r,date:day(r.date),name:r.description,method:{cash:'Tiền mặt',transfer:'Chuyển khoản',card:'Thẻ'}[r.method]||r.method}));rows.openingAccounts=(await read('DTAIKHOANNGANHANG')).map(r=>({id:r.ID,name:r.NAME,amount:round(r.SODUDAU)}));return rows;}
 if(source==='repairs'||source==='receptions'||source==='quotes')return (await normalize({repairs:'TLENHSUACHUA',receptions:'TTIEPNHANXE',quotes:'TBAOGIA'}[source])).map(r=>({...r,status:source==='quotes'?(r.NGAYDUYET?'Đã duyệt':'Chờ duyệt'):({repairs:['Mới','Đang sửa','Tạm dừng','Hoàn thành','Đã giao'],receptions:['Mới','Đang xử lý','Hoàn thành','Đã giao']}[source][Number(r.TRANGTHAI)]||r.status)}));
 if(source==='supplements'){const out=[];for(const r of await normalize('TPHATSINHSUACHUA')){const l=(await map('TLENHSUACHUA')).get(r.TLENHSUACHUAID);out.push({...r,code:l?.NAME||'',plate:(await map('DXE')).get(l?.DXEID)?.BIENSO||'',name:r.LYDO,status:({draft:'Nháp',pending:'Chờ duyệt',approved:'Đã duyệt',rejected:'Từ chối',applied:'Đã áp dụng'}[r.TRANGTHAI]||r.status)});}return out;}
 if(source==='workflow'){const states=new Map((await read('TWORKFLOWMAP')).map(r=>[Number(r.STT_WORKFLOW),r.TEN]));await map('TLENHSUACHUA');return (await normalize('TTRANGTHAIXE')).map(r=>({...r,code:r.TLENHSUACHUAID?(maps.TLENHSUACHUA?.get(r.TLENHSUACHUAID)?.NAME||r.TLENHSUACHUAID):r.code,date:day(r.NGAY_TRANGTHAI||r.NGAY_VAO),due:day(r.NGAY_DUKIEN),status:states.get(Number(r.TRANGTHAI))||String(r.TRANGTHAI),stage:Number(r.TRANGTHAI)}));}
 if(source==='warranties')return (await normalize('TBAOHANH')).map(r=>({...r,name:r.KETQUAXULY||r.name,end:day(r.NGAYKETTHUC),amount:round(r.CHIPHI),result:r.KETQUAXULY||'',status:!r.NGAYKETTHUC?'Chưa có hạn':day(r.NGAYKETTHUC)<today()?'Hết hạn':'Còn hạn'}));
 if(source==='maintenance')return (await normalize('TLICHSUBAODUONG')).map(r=>({...r,name:r.LOAIBAODUONG||r.name,date:day(r.NGAY_LANCUOI),due:day(r.NGAY_DUKIEN),odo:r.ODO_DUKIEN,currentOdo:(maps.DXE?.get(r.DXEID))?.ODO}));
 if(source==='commissions'||source==='payroll'){
  const month=(f.from||today()).slice(0,7);const data=await require('./employeeCommissions').load(query,{from:f.from,to:f.to,month});
  if(source==='commissions')return data.data.map(r=>({id:r.ID,code:r.SO_PHIEU,date:day(r.NGAYPHANCONG),plate:r.BIENSO,partner:r.TEN_KH,employee:r.TEN_NV,employeeKey:r.DNHANVIENID,allocated:round(r.HOAHONG),eligible:r.ELIGIBLE?round(r.HOAHONG):0,pending:r.ELIGIBLE?0:round(r.HOAHONG),TLENHSUACHUAID:r.TLENHSUACHUAID}));
  if(f.to&&f.to.slice(0,7)!==month)throw fail('Bảng lương: chọn khoảng ngày trong cùng một tháng.');
  const out=[];for(const r of data.payroll)out.push({id:r.ID,code:r.TEN_BANG_LUONG,date:`${month}-01`,employee:await label('DNHANVIEN',r.DNHANVIENID),base:round(r.LUONGCOBAN),allocated:round(r.HOAHONG),bonus:round(r.THUONG),deduction:round(r.PHAT),amount:round(r.TONGCONG)});return out;
 }
 if(source==='paymentDetails'){const out=[];for(const r of await read('TCHITIETTHANHTOAN')){const repair=!!r.THOADONSUACHUAID;const doc=(await map(repair?'THOADONSUACHUA':'TDONHANG')).get(r.THOADONSUACHUAID||r.TDONHANGID);if(!doc||!(await read(repair?'THOADONSUACHUA':'TDONHANG')).some(d=>d.ID===doc.ID))continue;out.push({id:r.ID,code:doc.NAME,date:day(r.NGAY),source:repair?'Sửa chữa':'Bán phụ tùng',partner:await label('DKHACHHANG',doc.DKHACHHANGID),method:['Tiền mặt','Chuyển khoản','Thẻ'][r.LOAI],account:await label('DTAIKHOANNGANHANG',r.DTAIKHOANNGANHANGID),amount:round(r.SOTIEN)});}return out;}
 if(/(Debt|Ledger)$/.test(source)){
  const ledger=await require('./debts').ledger(query);const partners=source.startsWith('customer')?ledger.receivable:ledger.payable;const out=[];
  for(const p of partners){const hist=p.history.map(h=>({...h,date:day(h.date||h.created)}));let opening=round(hist.filter(h=>f.from&&h.date<f.from).reduce((a,h)=>a+h.total-h.payment,0));const entries=hist.filter(h=>(!f.from||h.date>=f.from)&&(!f.to||h.date<=f.to));let balance=opening;
   for(const h of entries){balance=round(balance+h.total-h.payment);if(source.endsWith('Ledger'))out.push({id:h.id,code:h.code,date:h.date,partner:p.customer,source:h.source,amount:h.total,paid:h.payment,closing:balance});}
   if(source.endsWith('Debt'))out.push({id:p.id,name:p.customer,partner:p.customer,opening,amount:round(entries.reduce((a,h)=>a+h.total,0)),paid:round(entries.reduce((a,h)=>a+h.payment,0)),closing:balance});
  }return out;
 }
 // Inventory movements require both active header and active detail. Quantities are stored base units.
 const movements=async()=>{
  const out=[];const parts=await map('DMATHANG');const add=async(r,h,kind,date,received,issued,warehouse)=>{const p=parts.get(r.DMATHANGID);out.push({id:r.ID,code:h.NAME||'',date:day(date),source:kind,partId:r.DMATHANGID,nameKey:r.DMATHANGID,name:p?.NAME||'Chưa xác định hàng',partCode:p?.CODE||'',group:await label('DNHOMMATHANG',p?.DNHOMMATHANGID),warehouse:await label('DKHOHANG',warehouse),unit:await label('DDONVITINH',p?.DDONVITINHID),plate:(await map('DXE')).get(h.DXEID||r.DXEID)?.BIENSO||'',partner:await label(h.DNHACUNGCAPID?'DNHACUNGCAP':'DKHACHHANG',h.DNHACUNGCAPID||h.DKHACHHANGID),quantity:round(received||issued),received:round(received),issued:round(issued),price:round(r.DONGIA),amount:round(r.THANHTIEN),minimum:Number(p?.TONTOITHIEU||0),currentPrice:round(p?.GIANHAP),TLENHSUACHUAID:h.TLENHSUACHUAID||(kind==='Sửa chữa'?h.ID:null)});};
  const receipts=new Map((await read('TNHAPKHO')).map(r=>[r.ID,r]));for(const r of await read('TNHAPKHOCHITIET')){const h=receipts.get(r.TNHAPKHOID);if(h){if(r.DDONVITINHID&&parts.get(r.DMATHANGID)?.DDONVITINHID&&r.DDONVITINHID!==parts.get(r.DMATHANGID).DDONVITINHID)throw fail('Có nhập hàng khác đơn vị cơ sở; cần xác minh quy đổi trước khi tính kho.',422);await add(r,h,'Nhập kho',h.NGAY,r.SOLUONG,0,r.DKHOHANGID||h.DKHOHANGID);}}
  const sales=new Map((await read('TDONHANG')).filter(r=>Number(r.LOAI)===0).map(r=>[r.ID,r]));for(const r of await read('TDONHANGCHITIET')){const h=sales.get(r.TDONHANGID);if(h){if(r.DDONVITINHID&&parts.get(r.DMATHANGID)?.DDONVITINHID&&r.DDONVITINHID!==parts.get(r.DMATHANGID).DDONVITINHID)throw fail('Có bán hàng khác đơn vị cơ sở; cần xác minh quy đổi.',422);await add(r,h,'Bán phụ tùng',h.NGAY,r.SLNHAP,r.SLXUAT,r.DKHOHANGID||h.DKHOXUATID);}}
  const repairs=new Map((await read('TLENHSUACHUA')).map(r=>[r.ID,r]));for(const r of await read('TXUATPHUTUNG')){const h=repairs.get(r.TLENHSUACHUAID);if(h){if(Number(r.SLHOAN)>0)throw fail('Có hoàn kho phụ tùng thiếu ngày hoàn; chưa thể tính kho lịch sử chính xác.',422);await add(r,h,'Sửa chữa',r.NGAYXUAT,0,r.SOLUONG,r.DKHOHANGID);}}
  return out;
 };
 if(['movements','receiptMovements','outMovements','repairMovements','soldParts','stock'].includes(source)){let rows=await movements();if(source==='receiptMovements')rows=rows.filter(r=>r.source==='Nhập kho');if(source==='outMovements')rows=rows.filter(r=>r.issued);if(source==='repairMovements')rows=rows.filter(r=>r.source==='Sửa chữa');if(source==='soldParts')rows=rows.filter(r=>r.source==='Bán phụ tùng');return rows;}
 if(source==='repairServices'){const parents=new Map((await normalize('TLENHSUACHUA')).map(r=>[r.ID,r]));const out=[];for(const r of await read('TLENHSUACHUACHITIET')){const h=parents.get(r.TLENHSUACHUAID);if(h&&r.DDICHVUID)out.push({...h,id:r.ID,name:await label('DDICHVU',r.DDICHVUID),quantity:round(r.SOLUONG),price:round(r.DONGIA),amount:round(r.THANHTIEN),TLENHSUACHUAID:h.ID});}return out;}
 throw fail('Nguồn báo cáo chưa được triển khai.',422);
}
function match(row,f,period=true){if(period&&((f.from&&(!row.date||row.date<f.from))||(f.to&&(!row.date||row.date>f.to))))return false;for(const k of ['partner','plate','employee','warehouse','status','account','method'])if(f[k]&&String(row[k]||'')!==f[k])return false;return !f.q||Object.values(row).some(v=>typeof v!=='object'&&String(v??'').toLocaleLowerCase('vi').includes(f.q.toLocaleLowerCase('vi')));}
function aggregate(rows,key,columns){const groups=new Map();for(const r of rows){const name=key==='month'?r.date?.slice(0,7):key==='date'?r.date:r[key];const label=name||'Chưa xác định';const identity=r[key+'Key']||label;if(!groups.has(identity))groups.set(identity,{id:identity,name:label,count:0,jobs:0,_jobs:new Set()});const g=groups.get(identity);g.count++;if(r.TLENHSUACHUAID||r.id)g._jobs.add(r.TLENHSUACHUAID||r.id);for(const c of columns)if(['money','number'].includes(c.type)&&!['count','jobs'].includes(c.key))g[c.key]=round((g[c.key]||0)+Number(r[c.key]||0));}return [...groups.values()].map(({_jobs,...r})=>({...r,jobs:_jobs.size}));}
function calculate(report,raw,f){
 let rows=raw;const meta={};const notes=[];
 if(report.source==='stock'||report.stockLedger){
  const groups=new Map();const selected=raw.filter(r=>match(r,{...f,from:'',to:'',q:''},false)&&(!f.to||r.date<=f.to)); if(report.stockLedger&&f.q){const chosen=new Set(selected.filter(r=>(r.name+' '+r.partCode).toLocaleLowerCase('vi').includes(f.q.toLocaleLowerCase('vi'))).map(r=>r.partId));for(let i=selected.length-1;i>=0;i--)if(!chosen.has(selected[i].partId))selected.splice(i,1);}
  for(const r of selected){const key=r.partId+'|'+r.warehouse;if(!groups.has(key))groups.set(key,{id:key,code:r.partCode,name:r.name,warehouse:r.warehouse,unit:r.unit,opening:0,received:0,issued:0,closing:0,minimum:r.minimum,price:r.currentPrice,last:''});const g=groups.get(key);if(f.from&&r.date<f.from)g.opening=round(g.opening+r.received-r.issued);else{g.received=round(g.received+r.received);g.issued=round(g.issued+r.issued);}if(r.issued&&r.date>g.last)g.last=r.date;}
  for(const g of groups.values()){g.closing=round(g.opening+g.received-g.issued);g.estimated=round(g.closing*g.price);g.days=g.last?Math.floor((Date.parse(f.to||today())-Date.parse(g.last))/86400000):null;}
  if(report.stockLedger){const balances=new Map([...groups].map(([k,v])=>[k,v.opening]));rows=selected.filter(r=>match(r,{...f,q:''})).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id)).map(r=>{const key=r.partId+'|'+r.warehouse;const closing=round((balances.get(key)||0)+r.received-r.issued);balances.set(key,closing);return {...r,closing};});notes.push('Số dư chạy riêng theo phụ tùng và kho. Tìm kiếm chỉ chọn phụ tùng, không loại giao dịch trong thẻ kho.');}
  else rows=[...groups.values()].filter(r=>report.stockFilter==='low'?r.closing<r.minimum:report.stockFilter==='negative'?r.closing<0:report.stockFilter==='slow'?r.closing>0&&r.days!=null&&r.days>=f.days:true).filter(r=>match(r,{q:f.q},false));
  notes.push('Tồn tính từ giao dịch đang sử dụng; chưa có nguồn tồn ban đầu độc lập. Hàng chưa có lần xuất không được suy đoán số ngày tồn lâu.');
 }else if(report.ledger){rows=raw.filter(r=>report.ledger==='cash'?r.method==='Tiền mặt':['Chuyển khoản','Thẻ'].includes(r.method));const base=rows.filter(r=>match(r,{...f,q:'',from:'',to:''},false));let balances=new Map(report.ledger==='bank'?(raw.openingAccounts||[]).filter(a=>!f.account||a.name===f.account).map(a=>[a.id,a.amount]):[]);for(const r of base){const key=report.ledger==='cash'?'cash':r.accountId||'unassigned';if(!balances.has(key))balances.set(key,0);if(f.from&&r.date<f.from)balances.set(key,round(balances.get(key)+r.income-r.expense));}meta.opening=round([...balances.values()].reduce((a,v)=>a+v,0));rows=base.filter(r=>match(r,{...f,q:''})).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id)).map(r=>{const key=report.ledger==='cash'?'cash':r.accountId||'unassigned';const closing=round((balances.get(key)||0)+r.income-r.expense);balances.set(key,closing);return {...r,closing};});meta.closing=round([...balances.values()].reduce((a,v)=>a+v,0));if(f.q)rows=rows.filter(r=>match(r,{q:f.q},false));notes.push('Số dư theo giao dịch đã ghi nhận. Đã cộng số dư khởi tạo tài khoản. Tiền mặt chưa có số dư khởi tạo độc lập; tổng hợp nhiều tài khoản là tổng số dư.');
 }else rows=rows.filter(r=>match(r,f,report.period!==false&&!/(Debt|Ledger)$/.test(report.source)));
 if(report.completed)rows=rows.filter(r=>r.stage>=3);
 if(report.late)rows=rows.filter(r=>r.stage<3&&r.due&&r.due<today());
 if(report.activeWarranty)rows=rows.filter(r=>r.end&&r.end>=today());
 if(report.expiring){const limit=new Date(Date.parse(today())+f.days*86400000).toISOString().slice(0,10);rows=rows.filter(r=>r.end&&r.end>=today()&&r.end<=limit);}
 if(report.maintenanceDue)rows=rows.filter(r=>(r.due&&r.due<=today())||(Number(r.odo)>0&&Number(r.currentOdo)>=Number(r.odo)));
 if(report.advance)rows=rows.filter(r=>r.closing<0);
 const uniqueJobs=new Set(rows.map(r=>r.TLENHSUACHUAID||r.id));if(report.aggregate)rows=aggregate(rows,report.aggregate,report.columns);if(report.id==='customer-return')rows=rows.filter(r=>r.jobs>1);
 if(/(Debt|Ledger)$/.test(report.source))notes.push('Thanh toán tích lũy trên chứng từ cũ được phân bổ vào ngày chứng từ theo sổ công nợ hiện tại. Chưa đủ lịch sử để chứng nhận số dư tại ngày quá khứ.');
 if(['invoices','repairInvoices','saleInvoices'].includes(report.source))notes.push('Giá trị hóa đơn gồm chứng từ đang sử dụng, kể cả chưa thanh toán đủ. Đã thanh toán/còn lại là trạng thái hiện tại, không phải dòng tiền trong kỳ.');
 if(report.source==='cash')notes.push('Giao dịch chưa có lịch sử thanh toán chi tiết dùng ngày hóa đơn. Thanh toán nhập kho cũ chưa xác định phương thức được sổ quỹ hiện tại xếp tiền mặt.');
 if(report.source==='commissions')notes.push('Số lệnh dựa trên phân công đã có tỷ lệ chia. Tổng số lệnh đếm duy nhất, không cộng trùng lệnh nhiều KTV.');if(report.source==='payroll')notes.push('Lương lấy theo tháng chứa ngày bắt đầu. Bảng lương không chứng minh đã chi trả.');
 const totals={};for(const c of report.columns)if(['money','number'].includes(c.type)&&!['price','minimum','odo','days','closing'].includes(c.key))totals[c.key]=round(rows.reduce((sum,r)=>sum+Number(r[c.key]||0),0));
 if(report.columns.some(c=>c.key==='jobs'))totals.jobs=uniqueJobs.size;return {rows:rows.sort((a,b)=>String(a.date||a.name||'').localeCompare(String(b.date||b.name||''))||String(a.id).localeCompare(String(b.id))),totals,meta,notes};
}
async function run(id,input,user,query=db.query){const report=reports.find(r=>r.id===id);if(!report)throw fail('Không tìm thấy báo cáo.',404);if(!permitted(user,report))throw fail('Không có quyền xem báo cáo này.',403);if(report.available===false)throw fail(report.reason,422);const filters=validate(input);const raw=await sources(report.source,filters,query);const options={};for(const k of ['partner','plate','employee','warehouse','status','account','method'])options[k]=[...new Set(raw.map(r=>r[k]).filter(Boolean))].sort();const result=calculate(report,raw,filters);if(result.rows.length>20000)throw fail('Kết quả vượt 20.000 dòng; vui lòng thu hẹp kỳ hoặc bộ lọc.',413);return {report,filters,options,...result,createdAt:new Date().toISOString()};}
module.exports={run,sources,calculate,validate,match,aggregate,day,today,round,fail};
