const router=require('express').Router();const crypto=require('crypto');
const catalog=require('../services/reportCatalog');const data=require('../services/reportData');const exportsService=require('../services/reportExport');
const snapshots=new Map();const ttl=15*60*1000;
function cleanup(){for(const [key,r] of snapshots)if(Date.now()-r.time>ttl)snapshots.delete(key);}
function snapshot(req){cleanup();const entry=snapshots.get(req.params.snapshot);if(!entry||entry.owner!==req.accessUser.ID||entry.tenant!==require('../tenancy').key())throw data.fail('Kết quả đã hết hạn. Hãy xem báo cáo lại.',410);if(!catalog.permitted(req.accessUser,entry.result.report,req.path.endsWith('/pdf')||req.path.endsWith('/excel')))throw data.fail('Không có quyền xem và xuất/in báo cáo.',403);return entry.result;}
const handler=fn=>async(req,res)=>{try{res.set('Cache-Control','no-store');await fn(req,res);}catch(e){res.status(e.status||e.statusCode||500).json({error:e.message});}};
router.get('/presentation',handler(async(req,res)=>{if(!catalog.reports.some(r=>catalog.permitted(req.accessUser,r)))throw data.fail('Không có quyền xem báo cáo.',403);res.json(await require('../services/reportPresentation').companyPresentation());}));
router.get('/catalog',handler(async(req,res)=>res.json({groups:catalog.groups,reports:catalog.reports.filter(r=>catalog.permitted(req.accessUser,r)).map(r=>({...r,canExport:catalog.permitted(req.accessUser,r,true)}))})));
router.get('/run/:id',handler(async(req,res)=>{cleanup();const result=await data.run(req.params.id,req.query,req.accessUser);const key=crypto.randomUUID();const owned=[...snapshots].filter(([,v])=>v.owner===req.accessUser.ID&&v.tenant===require('../tenancy').key());if(owned.length>=10)snapshots.delete(owned[0][0]);if(snapshots.size>=100)snapshots.delete(snapshots.keys().next().value);while(snapshots.size&&[...snapshots.values()].reduce((n,v)=>n+v.result.rows.length,0)+result.rows.length>100000)snapshots.delete(snapshots.keys().next().value);result.rows=result.rows.map(row=>Object.fromEntries([...result.report.columns.map(c=>[c.key,row[c.key]??null]),['id',row.id],['ID',row.ID],['TLENHSUACHUAID',row.TLENHSUACHUAID]]));snapshots.set(key,{tenant:require('../tenancy').key(),owner:req.accessUser.ID,time:Date.now(),result});res.json({snapshot:key,createdAt:result.createdAt,filters:result.filters,options:result.options,notes:result.notes,totals:result.totals,meta:result.meta,total:result.rows.length,columns:result.report.columns});}));
router.get('/snapshots/:snapshot/rows',handler(async(req,res)=>{const result=snapshot(req);const page=Number(req.query.page||1);const pageSize=Number(req.query.pageSize||50);if(!Number.isInteger(page)||page<1||!Number.isInteger(pageSize)||pageSize<1||pageSize>200)throw data.fail('Phân trang không hợp lệ.');res.json({data:result.rows.slice((page-1)*pageSize,page*pageSize).map(r=>({id:r.id,...Object.fromEntries(result.report.columns.map(c=>[c.key,r[c.key]??null])),hasDocument:!!(r.TLENHSUACHUAID||r.TDONHANGID||r.ID||r.id)})),total:result.rows.length});}));
router.get('/snapshots/:snapshot/excel',handler(async(req,res)=>{require('../permissionPolicy').assert(req.accessUser,'EXPORT');const result=snapshot(req);res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').attachment(result.report.id+'.xlsx').send(exportsService.xlsx(result));}));
router.get('/snapshots/:snapshot/pdf',handler(async(req,res)=>{const result=snapshot(req);if(result.rows.length>2000)throw data.fail('Bản in tối đa 2.000 dòng. Thu hẹp bộ lọc hoặc xuất Excel.',413);const layout=req.query.layout||'landscape';if(!['landscape','portrait'].includes(layout))throw data.fail('Khổ in không hợp lệ.');res.type('application/pdf').send(await exportsService.pdf(result,layout));}));
router.get('/snapshots/:snapshot/document/:id',handler(async(req,res)=>{const result=snapshot(req);const row=result.rows.find(r=>String(r.id)===req.params.id);if(!row)throw data.fail('Không tìm thấy dòng.',404);const repair=row.TLENHSUACHUAID||(result.report.source==='repairs'?row.ID:null);if(repair&&(Number(req.accessUser.ISADMIN)===1||(Number(req.accessUser.permissions.REPAIR)&1)===1))return res.json({url:'/sua-chua?repairId='+encodeURIComponent(repair)});res.json({data:Object.fromEntries(result.report.columns.map(c=>[c.label,row[c.key]??null]))});}));
module.exports=router;
