import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';
import './SaasPages.css';
const client=axios.create({baseURL:'/api/saas/admin',timeout:15000});
client.interceptors.request.use(config=>{const token=sessionStorage.getItem('garage_platform_token');if(token)config.headers.Authorization='Bearer '+token;return config;});
export default function PlatformPage(){
  const [needsSetup,setNeedsSetup]=useState(false),[confirmation,setConfirmation]=useState('');
  useEffect(()=>{client.get('/setup-status').then(r=>setNeedsSetup(r.data.needsSetup)).catch(()=>{});},[]);
  const [token,setToken]=useState(sessionStorage.getItem('garage_platform_token')),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[rows,setRows]=useState([]),[operations,setOperations]=useState(null),[offset,setOffset]=useState(0),[more,setMore]=useState(false),[selected,setSelected]=useState(null),[action,setAction]=useState('extend'),[days,setDays]=useState(30),[reason,setReason]=useState('');
  async function load(){try{const [r,o]=await Promise.all([client.get('/tenants',{params:{offset}}),client.get('/operations')]);setRows(r.data.data);setMore(r.data.hasMore);setOperations(o.data);setError('');}catch(e){setError(e.response?.data?.error||'Chưa tải được dữ liệu.');if(e.response?.status===401){sessionStorage.removeItem('garage_platform_token');setToken(null);}}}
  useEffect(()=>{if(token)load();},[token,offset]);
  async function login(e){e.preventDefault();setBusy(true);setError('');try{if(needsSetup){if(password!==confirmation)throw Error('Hai mật khẩu chưa khớp.');await client.post('/setup',{password});setNeedsSetup(false);setConfirmation('');}const r=await client.post('/login',{password});sessionStorage.setItem('garage_platform_token',r.data.token);setToken(r.data.token);setPassword('');}catch(e){setError(e.response?.data?.error||e.message||'Chưa đăng nhập được.');}finally{setBusy(false);}}
  async function logout(){try{await client.post('/logout');}finally{sessionStorage.removeItem('garage_platform_token');setToken(null);setRows([]);setOperations(null);}}
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{await client.post('/tenants/'+encodeURIComponent(selected.ID)+'/'+action,{days:Number(days),reason});setSelected(null);setReason('');await load();}catch(e){setError(e.response?.data?.error||'Chưa cập nhật được.');}finally{setBusy(false);}}
  const date=value=>value?new Date(value).toLocaleString('vi-VN'):'—';
  return <main className="saas-page"><section className={'saas-card '+(token?'wide':'')}><Link to="/login" className="saas-brand">KAZUKO Auto</Link><h1>Quản trị nền tảng</h1><p>Quản lý cửa hàng đăng ký, thời hạn sử dụng và tình trạng khởi tạo.</p>{error&&<p role="alert" className="saas-error">{error}</p>}
    {!token?<form onSubmit={login} className="saas-form">{needsSetup&&<p>Thiết lập mật khẩu quản trị lần đầu trên localhost. Mật khẩu riêng này dùng để quản lý và gia hạn các cửa hàng.</p>}<label>{needsSetup?'Tạo mật khẩu quản trị (tối thiểu 12 ký tự)':'Mật khẩu quản trị nền tảng'}<input required type="password" value={password} minLength={needsSetup?12:undefined} maxLength={128} autoComplete={needsSetup?'new-password':'current-password'} onChange={e=>setPassword(e.target.value)}/></label>{needsSetup&&<label>Nhập lại mật khẩu<input required type="password" value={confirmation} autoComplete="new-password" onChange={e=>setConfirmation(e.target.value)}/></label>}<button disabled={busy} className="saas-button">{busy?'Đang xác minh…':needsSetup?'Thiết lập và đăng nhập':'Đăng nhập quản trị'}</button></form>:<>
      <div className="saas-actions"><button onClick={load}>Làm mới</button><button onClick={logout}>Đăng xuất</button></div>
      <div className="saas-table-wrap"><table className="saas-table"><thead><tr><th>Cửa hàng</th><th>Mã</th><th>Email</th><th>Số điện thoại</th><th>Trạng thái</th><th>Hạn sử dụng</th><th>Thao tác</th></tr></thead><tbody>{rows.map(row=><tr key={row.ID}><td>{row.NAME}</td><td>{row.SLUG}</td><td>{row.EMAIL}</td><td>{row.PHONE || "—"}</td><td>{row.STATE}</td><td>{date(row.ENDSAT)}</td><td><button onClick={()=>{setSelected(row);setAction(row.STATE==='failed'?'retry':row.STATE==='suspended'?'resume':'extend');setReason('');}}>Quản lý</button></td></tr>)}</tbody></table></div>
      <div className="saas-actions"><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-100))}>Trước</button><span>Trang {offset/100+1}</span><button disabled={!more} onClick={()=>setOffset(offset+100)}>Sau</button></div>
      {selected&&<form onSubmit={submit} className="saas-form"><h2>{selected.NAME}</h2><label>Thao tác<select value={action} onChange={e=>setAction(e.target.value)}><option value="extend">Gia hạn</option><option value="suspend">Khóa cửa hàng</option><option value="resume">Mở khóa</option><option value="retry">Thử lại khởi tạo lỗi</option></select></label>{action==='extend'&&<label>Số ngày gia hạn<input required type="number" min={1} max={365} value={days} onChange={e=>setDays(e.target.value)}/></label>}<label>Lý do<textarea required minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="saas-actions"><button className="saas-button" disabled={busy}>Lưu thay đổi</button><button type="button" onClick={()=>setSelected(null)}>Đóng</button></div></form>}
      <h2>Tác vụ khởi tạo</h2>{operations?.jobs.length?<ul>{operations.jobs.map(job=><li key={job.ID}>{job.TENANTID} — {job.STATE}, {job.ATTEMPTS} lần {job.ERROR&&'— '+job.ERROR}</li>)}</ul>:<p>Chưa có tác vụ.</p>}
      <h2>Sao lưu gần đây</h2>{operations?.backups.length?<ul>{operations.backups.map(row=><li key={row.ID}>{row.TENANTID} — {row.STATE} — {date(row.CREATED)}</li>)}</ul>:<p>Chưa có lịch sử sao lưu.</p>}
      <h2>Nhật ký quản trị</h2>{operations?.audit.length?<ul>{operations.audit.map((row,index)=><li key={index}>{date(row.CREATED)} — {row.ACTION} — {row.TENANTID}: {row.DETAIL}</li>)}</ul>:<p>Chưa có nhật ký.</p>}
    </>}</section></main>;
}
