import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { BarChart3, Download, FileText, Printer, RefreshCw, Search, X, ChevronLeft, ChevronRight } from 'lucide-react';
import api from '../api';
import './ReportCenterPage.css';
const localDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const initialFilters=()=>({from:localDate().slice(0,7)+'-01',to:localDate(),q:'',partner:'',plate:'',employee:'',warehouse:'',status:'',account:'',method:'',days:90});
const captions={partner:'Khách hàng / NCC',plate:'Biển số',employee:'Nhân viên',warehouse:'Kho',status:'Trạng thái',account:'Tài khoản',method:'Phương thức'};
function format(value,type){if(value==null)return '—';if(['money','number'].includes(type))return Number(value).toLocaleString('vi-VN',{maximumFractionDigits:2});if(type==='date')return String(value).split('-').reverse().join('/');return String(value);}
const message=e=>e.response?.data?.error||e.message;
function PaperHeader({company,report,result}) {
 const date=v=>v?.split('-').reverse().join('/');
 return <><div className="rc-paper-company">{company?.logo&&<img src={company.logo} alt="Logo gara"/>}<div><strong>{company?.name||'GARA'}</strong>{company?.address&&<p>Địa chỉ: {company.address}</p>}<p>{[company?.phone&&'Điện thoại: '+company.phone,company?.email&&'Email: '+company.email].filter(Boolean).join(' · ')}</p></div></div><h3>{report.name.toLocaleUpperCase('vi-VN')}</h3><p className="rc-paper-period">{report.period===false?'Danh mục tại thời điểm lập báo cáo':`Từ ngày ${date(result.filters.from)||'đầu dữ liệu'} đến ngày ${date(result.filters.to)||'hiện tại'}`}</p><p className="rc-paper-filters">{Object.entries({q:'Tìm kiếm',...captions}).filter(([k])=>result.filters[k]).map(([k,label])=>label+': '+result.filters[k]).join(' · ')}</p></>;
}
function PaperSignature({createdAt}) {
 const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(createdAt));
 const p=Object.fromEntries(parts.map(part=>[part.type,part.value]));
 return <div className="rc-paper-signature"><p>Ngày {p.day} tháng {p.month} năm {p.year}</p><strong>Người lập</strong><em>(Ký, họ tên)</em></div>;
}
function Plot({rows,columns}){const metrics=columns.filter(c=>['number','money'].includes(c.type)&&!['count','jobs'].includes(c.key));if(!metrics.length)metrics.push(...columns.filter(c=>c.type==='number'));const series=metrics.slice(0,2);const displayed=rows.slice(0,20);const max=Math.max(1,...displayed.flatMap(r=>series.map(c=>Math.abs(Number(r[c.key]||0)))));return <div className="rc-chart"><p>Biểu đồ các dòng trên trang hiện tại · {series.map(c=>c.label).join(' / ')}</p>{displayed.map(r=><div className="rc-bar-row" key={r.id}><span title={r.name}>{r.name}</span><div>{series.map((c,i)=><div key={c.key} className={`rc-bar color-${i}`} style={{width:`${Math.max(0,Math.abs(Number(r[c.key]||0))/max*100)}%`}}><b>{format(r[c.key],c.type)}</b></div>)}</div></div>)}</div>;}
export default function ReportCenterPage(){
 const navigate=useNavigate();const [company,setCompany]=useState(null);const [catalog,setCatalog]=useState(null),[group,setGroup]=useState('cash'),[selected,setSelected]=useState('receipts'),[find,setFind]=useState(''),[filters,setFilters]=useState(initialFilters),[applied,setApplied]=useState(''),[result,setResult]=useState(null),[rows,setRows]=useState([]),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[loadingRows,setLoadingRows]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState(false),[layout,setLayout]=useState('landscape'),[pdf,setPdf]=useState(''),[pdfBusy,setPdfBusy]=useState(false),[detail,setDetail]=useState(null),[exporting,setExporting]=useState(false);
 const frame=useRef(null),generation=useRef(0),pdfGeneration=useRef(0),pdfRef=useRef('');
 const report=catalog?.reports.find(r=>r.id===selected);const dirty=applied!==JSON.stringify(filters);const allowed=!!result&&!dirty&&!busy&&!loadingRows;
 const getCatalog=async()=>{setError('');try{const response=await api.get('/reports/center/catalog');setCatalog(response.data);const presentation=await api.get('/reports/center/presentation');setCompany(presentation.data);if(!response.data.reports.some(r=>r.id===selected)){setSelected(response.data.reports[0]?.id||'');setGroup(response.data.reports[0]?.group||'cash');}}catch(e){setError(message(e));}};
 useEffect(()=>{getCatalog();return()=>{generation.current++;pdfGeneration.current++;if(pdfRef.current)URL.revokeObjectURL(pdfRef.current);};},[]);
 useEffect(()=>{if(!result)return;const controller=new AbortController();setLoadingRows(true);api.get(`/reports/center/snapshots/${result.snapshot}/rows`,{params:{page,pageSize:50},signal:controller.signal}).then(r=>setRows(r.data.data)).catch(e=>{if(!controller.signal.aborted){setError(message(e));setRows([]);}}).finally(()=>{if(!controller.signal.aborted)setLoadingRows(false);});return()=>controller.abort();},[result,page]);
 const resetPdf=()=>{pdfGeneration.current++;if(pdfRef.current)URL.revokeObjectURL(pdfRef.current);pdfRef.current='';setPdf('');};
 const choose=id=>{generation.current++;setBusy(false);resetPdf();setPreview(false);setSelected(id);setResult(null);setRows([]);setDetail(null);setFilters(initialFilters());setError('');setPage(1);};
 const run=async()=>{const version=++generation.current;setBusy(true);setError('');setResult(null);setRows([]);resetPdf();const sent={...filters};try{const r=await api.get(`/reports/center/run/${selected}`,{params:sent,timeout:90000});if(version!==generation.current)return;setResult(r.data);setApplied(JSON.stringify(sent));setPage(1);}catch(e){if(version===generation.current)setError(message(e));}finally{if(version===generation.current)setBusy(false);}};
 const change=(key,value)=>setFilters(f=>({...f,[key]:value}));
 const download=async()=>{setExporting(true);setError('');try{const r=await api.get(`/reports/center/snapshots/${result.snapshot}/excel`,{responseType:'blob',timeout:90000});const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download=selected+'.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(await blobError(e));}finally{setExporting(false);}};
 const blobError=async e=>{if(e.response?.data instanceof Blob){try{return JSON.parse(await e.response.data.text()).error;}catch{}}return message(e);};
 const loadPdf=async()=>{const version=++pdfGeneration.current;setPdfBusy(true);setError('');if(pdfRef.current)URL.revokeObjectURL(pdfRef.current);setPdf('');try{const r=await api.get(`/reports/center/snapshots/${result.snapshot}/pdf`,{params:{layout},responseType:'blob',timeout:90000});if(version!==pdfGeneration.current)return;pdfRef.current=URL.createObjectURL(r.data);setPdf(pdfRef.current);}catch(e){if(version===pdfGeneration.current)setError(await blobError(e));}finally{if(version===pdfGeneration.current)setPdfBusy(false);}};
 const openRow=async row=>{try{const r=await api.get(`/reports/center/snapshots/${result.snapshot}/document/${encodeURIComponent(row.id)}`);if(r.data.url)navigate(r.data.url);else setDetail(r.data.data);}catch(e){setError(message(e));}};
 const filtered=catalog?.reports.filter(r=>(find?r.name.toLocaleLowerCase('vi').includes(find.toLocaleLowerCase('vi')):r.group===group))||[];
 return <main className="rc-page"><header className="rc-heading"><div><h1><BarChart3 size={25}/> Báo cáo Garage</h1><p>11 nhóm báo cáo · Dữ liệu từ chứng từ đã lưu</p></div><button onClick={getCatalog} disabled={busy}><RefreshCw size={16}/> Làm mới danh mục</button></header>
 {error&&<div className="rc-error" role="alert">{error}<button aria-label="Đóng thông báo" onClick={()=>setError('')}><X size={16}/></button></div>}
 <div className="rc-workspace"><aside className="rc-sidebar"><label className="rc-search"><Search size={16}/><input value={find} onChange={e=>setFind(e.target.value)} placeholder="Tìm báo cáo…"/></label><nav aria-label="Nhóm báo cáo">{catalog?.groups.map((g,i)=><button key={g.id} className={group===g.id?'active':''} onClick={()=>{setGroup(g.id);setFind('');const first=catalog.reports.find(r=>r.group===g.id);choose(first?.id||'');}}><span>{String(i+1).padStart(2,'0')}</span>{g.name}</button>)}</nav></aside>
 <section className="rc-content"><div className="rc-report-picker"><label>Báo cáo<select value={filtered.some(r=>r.id===selected)?selected:''} onChange={e=>{choose(e.target.value);setGroup(catalog.reports.find(r=>r.id===e.target.value)?.group||group);}}><option value="" disabled>Chọn báo cáo ({filtered.length})</option>{filtered.map(r=><option value={r.id} key={r.id}>{r.name}{r.available===false?' · Chưa đủ dữ liệu':''}</option>)}</select></label></div>
 {!catalog?<div className="rc-empty">Đang tải danh mục…</div>:!report?<div className="rc-empty">Chọn một báo cáo để bắt đầu.</div>:<><div className="rc-report-title"><h2>{report.name}</h2><span>{report.available===false?'Chưa đủ dữ liệu':'Chứng từ thực tế'}</span></div>
 {report.available===false?<div className="rc-empty rc-warning"><FileText size={28}/><h3>Chưa đủ dữ liệu để lập báo cáo</h3><p>{report.reason}</p></div>:<><div className="rc-filters">{report.period!==false&&<><label>Từ ngày<input type="date" value={filters.from} onChange={e=>change('from',e.target.value)}/></label><label>Đến ngày<input type="date" value={filters.to} onChange={e=>change('to',e.target.value)}/></label></>}<label>Tìm trong dữ liệu<input value={filters.q} onChange={e=>change('q',e.target.value)} placeholder="Mã, biển số, tên…"/></label>{Object.entries(captions).filter(([key])=>report.filters.includes(key)&&result?.options[key]?.length).map(([key,label])=><label key={key}>{label}<select value={filters[key]} onChange={e=>change(key,e.target.value)}><option value="">Tất cả</option>{result.options[key].map(v=><option key={v} value={v}>{v}</option>)}</select></label>)}{(selected==='stock-slow'||report.expiring)&&<label>{report.expiring?'Hết hạn trong số ngày':'Số ngày chưa xuất'}<input type="number" min="1" max="3650" value={filters.days} onChange={e=>change('days',e.target.value)}/></label>}<button className="primary" disabled={busy} onClick={run}><Search size={16}/>{busy?'Đang tính…':'Xem báo cáo'}</button><button disabled={busy} onClick={()=>setFilters(initialFilters())}>Đặt lại</button></div>
 <div className="rc-toolbar"><span>{result?`${result.total} dòng · Tạo ${new Date(result.createdAt).toLocaleString('vi-VN',{timeZone:'Asia/Bangkok'})}`:'Chọn bộ lọc và bấm Xem báo cáo'}</span><div><button disabled={!allowed||!report.canExport||exporting} onClick={download}><Download size={16}/> {exporting?'Đang xuất…':'Excel'}</button><button disabled={!allowed||!report.canExport} onClick={()=>{resetPdf();setPreview(true);}}><Printer size={16}/> In / PDF</button></div></div>
 {result&&dirty&&<p className="rc-warning">Bộ lọc đã thay đổi. Bấm Xem báo cáo để cập nhật kết quả và xuất/in.</p>}
 {result?.notes.map((note,i)=><p className="rc-note" key={i}>{note}</p>)}
 {result&&<div className="rc-kpis"><article><span>Số dòng kết quả</span><strong>{result.total.toLocaleString('vi-VN')}</strong></article>{Object.entries(result.totals).slice(0,5).map(([key,value])=><article key={key}><span>{result.columns.find(c=>c.key===key)?.label}</span><strong>{format(value,'number')}</strong></article>)}</div>}
 {report.chart&&rows.length>0&&<Plot rows={rows} columns={result.columns}/>}
 <div className={result?"rc-paper-viewer":""}><section className={result?"rc-paper":""}>{result&&<PaperHeader company={company} report={report} result={result}/>}<div className="rc-table-wrap"><table><thead><tr><th className="rc-stt">STT</th>{report.columns.map(c=><th key={c.key}>{c.label}</th>)}<th>Chi tiết</th></tr></thead><tbody>{!busy&&!loadingRows&&rows.map((row,index)=><tr key={row.id}><td className="rc-stt">{(page-1)*50+index+1}</td>{report.columns.map(c=><td className={['money','number'].includes(c.type)?'numeric':''} key={c.key}>{format(row[c.key],c.type)}</td>)}<td><button onClick={()=>openRow(row)} aria-label={`Xem ${row.code||row.name||'dòng báo cáo'}`}><FileText size={16}/></button></td></tr>)}</tbody>{result&&<tfoot><tr><td/>{report.columns.map((c,i)=><td key={c.key}>{i===0?'TỔNG CỘNG':result.totals[c.key]!=null?format(result.totals[c.key],c.type):'—'}</td>)}<td/></tr></tfoot>}</table>{(busy||loadingRows)&&<div className="rc-empty" role="status">Đang tải dữ liệu…</div>}{!busy&&!loadingRows&&!rows.length&&<div className="rc-empty">{result?'Không có dữ liệu phù hợp bộ lọc.':'Chưa chạy báo cáo.'}</div>}</div>{result&&<><p className="rc-paper-footnote">Tổng cộng tính trên toàn bộ {result.total} dòng. Trang dữ liệu {page} / {Math.max(1,Math.ceil(result.total/50))}; bản In / PDF gồm toàn bộ kết quả.</p><PaperSignature createdAt={result.createdAt}/></>}</section></div>
 {result&&<footer className="rc-pagination"><span>Trang {page} / {Math.max(1,Math.ceil(result.total/50))} · 50 dòng/trang</span><button disabled={page===1||busy||loadingRows} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/> Trước</button><button disabled={page*50>=result.total||busy||loadingRows} onClick={()=>setPage(p=>p+1)}>Sau <ChevronRight size={16}/></button></footer>}</> }</>}
 </section></div>
 {detail&&<div className="rc-overlay"><section className="rc-dialog rc-detail" role="dialog" aria-modal="true" aria-label="Chi tiết báo cáo"><header><h2>Chi tiết dòng báo cáo</h2><button onClick={()=>setDetail(null)} aria-label="Đóng"><X/></button></header><dl>{Object.entries(detail).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v??'—')}</dd></div>)}</dl></section></div>}
 {preview&&<div className="rc-overlay"><section className="rc-dialog" role="dialog" aria-modal="true" aria-label="Xem bản in báo cáo"><header><div><h2>{report.name}</h2><small>Bản in dùng đúng kết quả đã xem · {result.total} dòng</small></div><button onClick={()=>{resetPdf();setPreview(false);setPdfBusy(false);}} aria-label="Đóng"><X/></button></header><div className="rc-preview-controls"><label>Mẫu trình bày<select value={layout} disabled={pdfBusy} onChange={e=>{setLayout(e.target.value);resetPdf();}}><option value="landscape">A4 ngang</option><option value="portrait">A4 đứng</option></select></label><button disabled={pdfBusy} onClick={loadPdf}>{pdfBusy?'Đang tạo PDF…':'Xem bản in'}</button><button disabled={!pdf||pdfBusy} onClick={()=>frame.current?.contentWindow?.print()}><Printer size={16}/> In / Chọn máy in</button>{pdf&&<a className="rc-download" href={pdf} download={selected+'.pdf'}>Tải PDF</a>}</div>{error&&<p role="alert" className="rc-error">{error}</p>}{pdf?<iframe title="Bản PDF báo cáo" src={pdf} ref={frame}/>:<div className="rc-empty">{pdfBusy?'Đang tạo bản in…':'Chọn mẫu trình bày và bấm Xem bản in.'}</div>}</section></div>}
 </main>;
}
